# Input data dan membuat data frame

In [1]:
import pandas as pd
df_raw = pd.read_csv("ebay_womens_perfume.csv")
df_raw

,brand,title,type,price,priceWithCurrency,available,availableText,sold,lastUpdated,itemLocation
0,Carolina Herrera,Good Girl by Carolina Herrera 2.7 oz Eau De Pa...,Eau de Parfum,43.99,US $43.99/ea,2.0,2 available / 393 sold,393.0,"May 23, 2024 10:43:50 PDT","Thomasville, Alabama, United States"
1,As Shown,Parfums de Marly Delina La Rosee Eau de Parfum...,Eau de Parfum,79.99,US $79.99,5.0,5 available / 40 sold,40.0,"May 24, 2024 00:15:48 PDT","New Jersey, Hong Kong"
2,PRADA,PRADA Paradoxe by Prada EDP 3.0oz/90ml Spray P...,Eau de Parfum,59.99,US $59.99,10.0,More than 10 available / 35 sold,35.0,"May 14, 2024 20:54:25 PDT","Orange, New Jersey, United States"
3,As Show,J'adore Parfum D'eau by Christian 3.4 oz EDP F...,Eau de Parfum,59.99,US $59.99/ea,10.0,More than 10 available / 9 sold,9.0,"May 23, 2024 01:23:05 PDT","USA, New Jersey, Hong Kong"
4,Khadlaj,Shiyaaka for Men EDP Spray 100ML (3.4 FL.OZ) B...,Eau de Parfum,29.99,US $29.99/ea,10.0,More than 10 available,NaN,NaN,"Little Ferry, New Jersey, United States"
...,...,...,...,...,...,...,...,...,...,...
995,Avon,Avon Far Away Infinity Eau de Parfum 1.7 fl. o...,Eau de Parfum,13.89,US $13.89,10.0,More than 10 available / 157 sold,157.0,"May 16, 2024 22:35:29 PDT","West Palm Beach, Florida, United States"
996,Mancera,Roses Greedy by Mancera perfume for unisex EDP...,Eau de Parfum,57.85,US $57.85/ea,33.0,33 available / 58 sold,58.0,"May 24, 2024 08:03:11 PDT","Dallas, Texas, United States"
997,Unbranded,"Sweet Tooth Eau de Parfum, Perfume for Women, ...",1,30.96,US $30.96,2.0,2 available / 3 sold,3.0,"May 17, 2024 23:16:41 PDT","New York, New York, United States"
998,Juliette Has A Gun,MMMM BY Juliette Has A Gun perfume for her EDP...,Eau de Perfume,53.99,US $53.99/ea,3.0,3 available / 117 sold,117.0,"May 13, 2024 22:19:34 PDT","Dallas, Texas, United States"
999,Paris Hilton,PARIS HILTON ELECTRIFY for Women Cologne 3.4 o...,Eau de Parfum,14.99,US $14.99/ea,4.0,4 available / 51 sold,51.0,"May 22, 2024 05:44:45 PDT","TX, United States"

In [50]:
df_raw.columns

Index(['brand', 'title', 'type', 'price', 'priceWithCurrency', 'available',
       'availableText', 'sold', 'lastUpdated', 'itemLocation'],
      dtype='str')

# Pengecekan data secara menyeluruh

In [2]:
df_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   brand              999 non-null    str
 1   title              1000 non-null   str
 2   type               998 non-null    str
 3   price              1000 non-null   float64
 4   priceWithCurrency  1000 non-null   str
 5   available          869 non-null    float64
 6   availableText      992 non-null    str
 7   sold               984 non-null    float64
 8   lastUpdated        927 non-null    str
 9   itemLocation       1000 non-null   str
dtypes: float64(3), str(7)
memory usage: 260.2 KB

In [3]:
missing_value= ((df_raw.isna().sum() / len(df_raw)) * 100)      # % missing value
missing_value

brand                 0.1
title                 0.0
type                  0.2
price                 0.0
priceWithCurrency     0.0
available            13.1
availableText         0.8
sold                  1.6
lastUpdated           7.3
itemLocation          0.0
dtype: float64

In [4]:
df_raw.describe()

             price   available          sold
count  1000.000000  869.000000    984.000000
mean     39.892980   21.426928    497.321138
std      29.072186   51.476703   1372.510561
min       1.990000    2.000000      1.000000
25%      20.700000    6.000000     15.000000
50%      32.990000   10.000000     52.000000
75%      49.990000   10.000000    263.750000
max     299.990000  557.000000  17854.000000

In [5]:
df_raw.isnull().sum()

brand                  1
title                  0
type                   2
price                  0
priceWithCurrency      0
available            131
availableText          8
sold                  16
lastUpdated           73
itemLocation           0
dtype: int64

In [6]:
df_raw[df_raw["brand"].isna()]

,brand,title,type,price,priceWithCurrency,available,availableText,sold,lastUpdated,itemLocation
856,NaN,Bright Crystal de Versace Eau de Toilette 3.0 ...,NaN,29.99,US $29.99,NaN,2 disponibles / 3 vendidos,NaN,23 may 2024 02:42:14 EST,"Hamtramck, Michigan, Estados Unidos"

In [7]:
df_raw[df_raw["type"].isna()]

,brand,title,type,price,priceWithCurrency,available,availableText,sold,lastUpdated,itemLocation
463,As Show,Carmina By Creed EDP 75ml 2.5 oz Spray For Wom...,NaN,128.88,US $128.88,10.0,10 available / 21 sold,21.0,"May 24, 2024 00:32:16 PDT","New Jersey, United States, Hong Kong"
856,NaN,Bright Crystal de Versace Eau de Toilette 3.0 ...,NaN,29.99,US $29.99,NaN,2 disponibles / 3 vendidos,NaN,23 may 2024 02:42:14 EST,"Hamtramck, Michigan, Estados Unidos"

In [8]:
df_raw[df_raw["availableText"].isna()]

,brand,title,type,price,priceWithCurrency,available,availableText,sold,lastUpdated,itemLocation
121,Ellis Brooklyn,NWB Ellis Brooklyn Miami Nectar Eau de Parfum ...,Eau de Parfum,33.00,US $33.00,NaN,NaN,NaN,NaN,"Cranford, New Jersey, United States"
602,Giardini Di Toscana,Bianco Latte EDP by Giardini Di Toscana 100 M...,Perfume,140.00,US $140.00,NaN,NaN,NaN,NaN,"Houston, Texas, United States"
732,CHANEL,CHANEL Les Eaux De Chanel Paris Eau De Toilett...,Eau de Toilette,24.00,US $24.00,NaN,NaN,NaN,NaN,"Los Angeles, California, United States"
827,Ellis Brooklyn,NWB Ellis Brooklyn Biography Fragrance Discove...,Discovery Set,17.00,US $17.00,NaN,NaN,NaN,NaN,"Edison, New Jersey, United States"
839,Lomani,SPICE ADDICT PRIVATE COLLECTION BY LOMANI EDP ...,Eau de Parfum,84.00,US $84.00,NaN,NaN,NaN,NaN,"Hialeah, Florida, United States"
880,Burberry,Burberry Goddess EDP Eau De Parfum Spray 3.3 o...,Eau de Parfum,95.00,US $95.00,NaN,NaN,NaN,NaN,"West Hollywood, California, United States"
927,Snif,"Snif : Sweet Ash .07 FL. OZ. - Juniper, Fir Ba...",Perfume,14.95,US $14.95,NaN,NaN,NaN,NaN,"Philadelphia, Pennsylvania, United States"
983,Burberry,Burberry Her ELIXIR DE PARFUM EDP Intense-Delu...,Eau de Parfum,13.00,US $13.00,NaN,NaN,NaN,NaN,"Chino, California, United States"

In [9]:
df_raw[df_raw.duplicated(keep=False)]

,brand,title,type,price,priceWithCurrency,available,availableText,sold,lastUpdated,itemLocation
344,FLOWER,12 Piece Woman’s Perfume Lot: Assorted scents ...,Perfume,48.0,US $48.00,4.0,4 available / 1 sold,1.0,NaN,"Webster, Florida, United States"
662,FLOWER,12 Piece Woman’s Perfume Lot: Assorted scents ...,Perfume,48.0,US $48.00,4.0,4 available / 1 sold,1.0,NaN,"Webster, Florida, United States"

In [10]:
duplikat = df_raw.duplicated().sum() / len(df_raw) * 100   # % Duplikat
print ("Duplikat(%):",duplikat)

Duplikat(%): 0.1

## Hapus duplikat

In [11]:
df = df_raw.copy()
df = df.drop_duplicates()        #Data Frame baru untuk di cleaning
df[df.duplicated(keep=False)]

Empty DataFrame
Columns: [brand, title, type, price, priceWithCurrency, available, availableText, sold, lastUpdated, itemLocation]
Index: []

# Cleaning untuk brand, title, dan type

## Hapus spasi

In [12]:
df[["brand","title","type"]]=df[["brand","title","type"]].apply(
    lambda x : x.str.strip().str.replace(r'\s+', ' ', regex=True)
)
df

,brand,title,type,price,priceWithCurrency,available,availableText,sold,lastUpdated,itemLocation
0,Carolina Herrera,Good Girl by Carolina Herrera 2.7 oz Eau De Pa...,Eau de Parfum,43.99,US $43.99/ea,2.0,2 available / 393 sold,393.0,"May 23, 2024 10:43:50 PDT","Thomasville, Alabama, United States"
1,As Shown,Parfums de Marly Delina La Rosee Eau de Parfum...,Eau de Parfum,79.99,US $79.99,5.0,5 available / 40 sold,40.0,"May 24, 2024 00:15:48 PDT","New Jersey, Hong Kong"
2,PRADA,PRADA Paradoxe by Prada EDP 3.0oz/90ml Spray P...,Eau de Parfum,59.99,US $59.99,10.0,More than 10 available / 35 sold,35.0,"May 14, 2024 20:54:25 PDT","Orange, New Jersey, United States"
3,As Show,J'adore Parfum D'eau by Christian 3.4 oz EDP F...,Eau de Parfum,59.99,US $59.99/ea,10.0,More than 10 available / 9 sold,9.0,"May 23, 2024 01:23:05 PDT","USA, New Jersey, Hong Kong"
4,Khadlaj,Shiyaaka for Men EDP Spray 100ML (3.4 FL.OZ) B...,Eau de Parfum,29.99,US $29.99/ea,10.0,More than 10 available,NaN,NaN,"Little Ferry, New Jersey, United States"
...,...,...,...,...,...,...,...,...,...,...
995,Avon,Avon Far Away Infinity Eau de Parfum 1.7 fl. o...,Eau de Parfum,13.89,US $13.89,10.0,More than 10 available / 157 sold,157.0,"May 16, 2024 22:35:29 PDT","West Palm Beach, Florida, United States"
996,Mancera,Roses Greedy by Mancera perfume for unisex EDP...,Eau de Parfum,57.85,US $57.85/ea,33.0,33 available / 58 sold,58.0,"May 24, 2024 08:03:11 PDT","Dallas, Texas, United States"
997,Unbranded,"Sweet Tooth Eau de Parfum, Perfume for Women, ...",1,30.96,US $30.96,2.0,2 available / 3 sold,3.0,"May 17, 2024 23:16:41 PDT","New York, New York, United States"
998,Juliette Has A Gun,MMMM BY Juliette Has A Gun perfume for her EDP...,Eau de Perfume,53.99,US $53.99/ea,3.0,3 available / 117 sold,117.0,"May 13, 2024 22:19:34 PDT","Dallas, Texas, United States"
999,Paris Hilton,PARIS HILTON ELECTRIFY for Women Cologne 3.4 o...,Eau de Parfum,14.99,US $14.99/ea,4.0,4 available / 51 sold,51.0,"May 22, 2024 05:44:45 PDT","TX, United States"

## Mengisi mising kolom berdasarkan informasi "title"

In [13]:
df[df["type"].isna()]

,brand,title,type,price,priceWithCurrency,available,availableText,sold,lastUpdated,itemLocation
463,As Show,Carmina By Creed EDP 75ml 2.5 oz Spray For Wom...,NaN,128.88,US $128.88,10.0,10 available / 21 sold,21.0,"May 24, 2024 00:32:16 PDT","New Jersey, United States, Hong Kong"
856,NaN,Bright Crystal de Versace Eau de Toilette 3.0 ...,NaN,29.99,US $29.99,NaN,2 disponibles / 3 vendidos,NaN,23 may 2024 02:42:14 EST,"Hamtramck, Michigan, Estados Unidos"

In [14]:
df.loc[463, ['brand', 'type']] = ['Creed', 'Eau de Parfum']
df.loc[856, ['brand', 'type']] = ['Versace', 'Eau de Toilette']

## Membuat nama "brand" lebih konsisten

In [15]:
pd.set_option('display.max_rows', None)
df["brand"] = df["brand"].str.title()
df["brand"].value_counts().sort_index(ascending=True)

brand
Acqua Di Parma                  2
Adam Levine                     1
Aerin                           2
Aeropostale                     1
Afnan                           3
Ainash Perfums                  1
Al Hambra                       1
Al Haramain                     2
Al Rehab                        2
Al Wataniah                     2
Al-Rehab                        1
Alfred Sung                     5
Alt Fragrances                  2
Anna Sui                        2
Aquolina                        2
Ariana Grande                  25
Armaf                           8
Armand Dupree Fuller            1
As Picture Show                 1
As Show                        14
As Showed                       1
As Shown                       18
Assorted                        1
Asst                            1
Atelier Cologne                 1
Atlantic                        1
Avon                            7
Baby Phat                       1
Banana Republic                 1
Bath & Body Works               2
Bellie Eilish                   1
Benetton                        1
Boucheron                       1
Britney Spears                  8
Burberry                       22
Bvlgari                         4
Byredo                          2
Cacharel                        6
Calvin Klein                   17
Carolina Herrera               27
Chaka By Chaka Khan             1
Chanel                          9
Change For Women                1
Chloe                           1
Chloé                           1
Chopard                         1
Christian Audigier              3
Classic Erotica                 1
Clean                           3
Clinique                       11
Clubman Pinaud                  1
Coach                          15
Coty                            1
Creed                           5
Daddy Yankee                    1
Dana                            3
Davidoff                        4
Designer Series                 1
Dior                            4
Diptyque                        1
Dkny                            1
Dolce & Gabbana                13
Dolce Gabbana                   1
Dolce&Gabbana                  30
Donna Karan                     9
Dossier                        14
Elie Saab                       1
Elizabeth & James               1
Elizabeth And James Nirvana     1
Elizabeth Arden                12
Elizabeth Taylor                7
Ellis Brooklyn                  3
Escada                          6
Estee Lauder                    1
Estée Lauder                   12
Evyan                           2
Ex Nihilo                       1
Five Star Fragrance             1
Flower                          1
Fragonard                       4
Fragrance Couture               1
Fred Hayman                     1
Frederic Malle                  1
Fuller Armand Dupree            1
Gap                             2
Generic                         1
Gianni Versace                  3
Giardini Di Toscana             1
Giorgi^O Armani                 2
Giorgio Arm.Ani                 1
Giorgio Armani                 12
Giorgio Beverly Hills           2
Giorgio² Armani                 3
Givenchy                       13
Gloria Vanderbilt               1
Gloss Moderne                   1
Glossier                        1
Gucci                          16
Guerlain                        2
Guess                           3
Gwen Stefani                    2
Halston                         1
Hermès                          7
Hollister                       2
Huda Beauty                     1
Huda Beauty Kayali              1
Hugo Boss                       3
Issey Miyake                    2
J Lo                            1
J. Del Pozo                     2
Jean Couturier                  1
Jean Paul Gaultier              1
Jeanne Arthes                   1
Jennifer Lopez                  2
Jessica Mcclintock              2
Jessica Simpson                 3
Jimmy Choo                     13
Jlo                             1
Jo Malone                      29
Jovan                           2
Juicy Couture                  13
Juliette Has A Gun             12
Justin Bieber                   1
Kate Spade                      3
Kate Spade New York             1
Katy Perry                      2
Kenneth Cole                    1
Kenzo                           2
Khadlaj                         3
Kilian                         12
Kim Kardashian                  3
L'Artisan                       1
Lake&Skye                       1
Lancome                         4
Lancôme                        37
Lanvin                          5
Lattafa                        12
Lattafa Perfumes                1
Le Labo                         3
Liz Claiborne                   4
Lolita Lempicka                 1
Lomani                          1
Love Luxe Beauty                1
Lucky                           1
Maison                          1
Maison Alhambra                 9
Maison Margiela                 4
Maison Martin Margiela          1
Mancera                         3
Marc Jacobs                    14
Marilyn Miglin                  1
Mem                             1
Michael Kors                    6
Miim Miic                       1
Miraclelayer                    1
Montale                         3
Montblanc                       2
Moschino                        4
Multiple Brands                 1
M·A·C                           2
Narciso Rodriguez               9
Natalie                         1
Nest                            1
One Direction                   2
Oscar De La Renta               4
Ouai                            4
Pacifica                        1
Paco Rabanne                    2
Paloma Picasso                  1
Parfum                          1
Parfums                         1
Parfums De Marly               19
Parfums Gres                    1
Parfums Grès                    1
Paris Hilton                    4
Perfume                         1
Perfumer'S Workshop             1
Perry Ellis                     3
Philosophy                      6
Phlur                           1
Pink                            1
Pink Sugar                      1
Pleasing                        1
Prada                          11
Preferred Fragrance             1
Prince Matchabelli              1
Pure Romance                    1
Qrc                             1
Ralph Lauren                    9
Rasasi                          1
Revlon                          1
Rihanna                         1
Robert Piguet                   4
Roja                            1
Sabrina Carpenter               1
Salvatore Ferragamo             3
Sarah Jessica Parker            3
Sean John                       1
See Photo                       1
Sisley                          1
Snif                            1
Sol De Janeiro                  5
Spiritual Sky                   1
T.O.V.A.                        2
Taylor Swift                    2
Tf                              1
The Body Shop                   1
Thierry Mugler                 18
Tiffany & Co.                   1
Tiziana Terenzi                 1
Tom Ford                        4
Tommy Hilfiger                  1
Tory Burch                      1
Tous                            1
Tru Fragrance                   1
True Religion                   1
Ulta                            1
Unbranded                      11
United Colors Of Benetton       1
Urban Outfitters                1
Valentino                      11
Vera Wang                       3
Versace                        34
Vicki Tiel                      1
Victoria'S Secret              26
Viktor & Rolf                  10
Vilhelm Parfumerie              1
Vince Camuto                    1
Xerjoff                         1
Yardley London                  2
Ysl                             2
Yves Saint Laurent             25
Zara                            2
~ Crepe Erase ~                 1
Name: count, dtype: int64

In [16]:
brand_mapping = {
    'Dolce&Gabbana': 'Dolce & Gabbana',
    'Dolce Gabbana': 'Dolce & Gabbana',

    'Ysl': 'Yves Saint Laurent',

    'Giorgi^O Armani': 'Giorgio Armani',
    'Giorgio Arm.Ani': 'Giorgio Armani',
    'Giorgio² Armani': 'Giorgio Armani',

    'Lancome': 'Lancôme',

    'Estee Lauder': 'Estée Lauder',

    'Chloe': 'Chloé',

    'Parfums Gres': 'Parfums Grès',

    'Al-Rehab': 'Al Rehab',

    'J Lo': 'Jennifer Lopez',
    'Jlo': 'Jennifer Lopez',

    'Lattafa Perfumes': 'Lattafa',

    'Kate Spade New York': 'Kate Spade',

    'Maison Martin Margiela': 'Maison Margiela',

    'Elizabeth And James Nirvana': 'Elizabeth & James',

    'Gianni Versace': 'Versace',

    'Benetton': 'United Colors Of Benetton'
}
df["brand"] = df["brand"].replace(brand_mapping)
df["brand"].value_counts().sort_index(ascending=True)

brand
Acqua Di Parma                2
Adam Levine                   1
Aerin                         2
Aeropostale                   1
Afnan                         3
Ainash Perfums                1
Al Hambra                     1
Al Haramain                   2
Al Rehab                      3
Al Wataniah                   2
Alfred Sung                   5
Alt Fragrances                2
Anna Sui                      2
Aquolina                      2
Ariana Grande                25
Armaf                         8
Armand Dupree Fuller          1
As Picture Show               1
As Show                      14
As Showed                     1
As Shown                     18
Assorted                      1
Asst                          1
Atelier Cologne               1
Atlantic                      1
Avon                          7
Baby Phat                     1
Banana Republic               1
Bath & Body Works             2
Bellie Eilish                 1
Boucheron                     1
Britney Spears                8
Burberry                     22
Bvlgari                       4
Byredo                        2
Cacharel                      6
Calvin Klein                 17
Carolina Herrera             27
Chaka By Chaka Khan           1
Chanel                        9
Change For Women              1
Chloé                         2
Chopard                       1
Christian Audigier            3
Classic Erotica               1
Clean                         3
Clinique                     11
Clubman Pinaud                1
Coach                        15
Coty                          1
Creed                         5
Daddy Yankee                  1
Dana                          3
Davidoff                      4
Designer Series               1
Dior                          4
Diptyque                      1
Dkny                          1
Dolce & Gabbana              44
Donna Karan                   9
Dossier                      14
Elie Saab                     1
Elizabeth & James             2
Elizabeth Arden              12
Elizabeth Taylor              7
Ellis Brooklyn                3
Escada                        6
Estée Lauder                 13
Evyan                         2
Ex Nihilo                     1
Five Star Fragrance           1
Flower                        1
Fragonard                     4
Fragrance Couture             1
Fred Hayman                   1
Frederic Malle                1
Fuller Armand Dupree          1
Gap                           2
Generic                       1
Giardini Di Toscana           1
Giorgio Armani               18
Giorgio Beverly Hills         2
Givenchy                     13
Gloria Vanderbilt             1
Gloss Moderne                 1
Glossier                      1
Gucci                        16
Guerlain                      2
Guess                         3
Gwen Stefani                  2
Halston                       1
Hermès                        7
Hollister                     2
Huda Beauty                   1
Huda Beauty Kayali            1
Hugo Boss                     3
Issey Miyake                  2
J. Del Pozo                   2
Jean Couturier                1
Jean Paul Gaultier            1
Jeanne Arthes                 1
Jennifer Lopez                4
Jessica Mcclintock            2
Jessica Simpson               3
Jimmy Choo                   13
Jo Malone                    29
Jovan                         2
Juicy Couture                13
Juliette Has A Gun           12
Justin Bieber                 1
Kate Spade                    4
Katy Perry                    2
Kenneth Cole                  1
Kenzo                         2
Khadlaj                       3
Kilian                       12
Kim Kardashian                3
L'Artisan                     1
Lake&Skye                     1
Lancôme                      41
Lanvin                        5
Lattafa                      13
Le Labo                       3
Liz Claiborne                 4
Lolita Lempicka               1
Lomani                        1
Love Luxe Beauty              1
Lucky                         1
Maison                        1
Maison Alhambra               9
Maison Margiela               5
Mancera                       3
Marc Jacobs                  14
Marilyn Miglin                1
Mem                           1
Michael Kors                  6
Miim Miic                     1
Miraclelayer                  1
Montale                       3
Montblanc                     2
Moschino                      4
Multiple Brands               1
M·A·C                         2
Narciso Rodriguez             9
Natalie                       1
Nest                          1
One Direction                 2
Oscar De La Renta             4
Ouai                          4
Pacifica                      1
Paco Rabanne                  2
Paloma Picasso                1
Parfum                        1
Parfums                       1
Parfums De Marly             19
Parfums Grès                  2
Paris Hilton                  4
Perfume                       1
Perfumer'S Workshop           1
Perry Ellis                   3
Philosophy                    6
Phlur                         1
Pink                          1
Pink Sugar                    1
Pleasing                      1
Prada                        11
Preferred Fragrance           1
Prince Matchabelli            1
Pure Romance                  1
Qrc                           1
Ralph Lauren                  9
Rasasi                        1
Revlon                        1
Rihanna                       1
Robert Piguet                 4
Roja                          1
Sabrina Carpenter             1
Salvatore Ferragamo           3
Sarah Jessica Parker          3
Sean John                     1
See Photo                     1
Sisley                        1
Snif                          1
Sol De Janeiro                5
Spiritual Sky                 1
T.O.V.A.                      2
Taylor Swift                  2
Tf                            1
The Body Shop                 1
Thierry Mugler               18
Tiffany & Co.                 1
Tiziana Terenzi               1
Tom Ford                      4
Tommy Hilfiger                1
Tory Burch                    1
Tous                          1
Tru Fragrance                 1
True Religion                 1
Ulta                          1
Unbranded                    11
United Colors Of Benetton     2
Urban Outfitters              1
Valentino                    11
Vera Wang                     3
Versace                      37
Vicki Tiel                    1
Victoria'S Secret            26
Viktor & Rolf                10
Vilhelm Parfumerie            1
Vince Camuto                  1
Xerjoff                       1
Yardley London                2
Yves Saint Laurent           27
Zara                          2
~ Crepe Erase ~               1
Name: count, dtype: int64

In [17]:
df[df["brand"] == "Tf"]     #Filter untuk membantu pembuatan mapping

,brand,title,type,price,priceWithCurrency,available,availableText,sold,lastUpdated,itemLocation
329,Tf,Lost Cherry Eau de Parfum 3.4 oz / 100ml For W...,Eau de Parfum,69.99,US $69.99/ea,4.0,4 available / 7 sold,7.0,"May 23, 2024 18:24:39 PDT","California,United States, Hong Kong"

## Membuat nama "type" lebih konsisten

In [18]:
df["type"] = (
    df["type"].str.lower()
)
df["type"].value_counts(dropna=False).sort_index(ascending=True)

type
/                                                 1
1                                                 1
3 pc                                              1
asst                                              1
bath oil                                          1
beauty                                            1
body lotion                                       1
body mist                                         1
body powder                                       1
body spray                                        1
cologne                                           3
cologne spray                                     1
cream                                             1
deodorant                                         1
deodorant stick                                   1
discovery set                                     1
does not apply                                    2
eau de cologne                                   38
eau de parfum                                   579
eau de parfum 2 pcs set                           1
eau de parfum 3 pcs set                           1
eau de parfum spray (unisex tester) 3.4 oz        1
eau de parfum supreme                             1
eau de parfum, eau de parfume                     1
eau de parfum, spray                              1
eau de parfum/perfume                             1
eau de parfume                                    2
eau de perfume                                   23
eau de toilette                                 192
eau de toilette spray 3.4 oz                      1
eau de toilette, spray                            6
edp                                               1
edp and parfum                                    1
edt                                               1
elixir de parfum                                  1
esprit de parfum                                  2
extract parfum                                    1
extrait de parfum                                 3
fine fragrance mist                               1
fragrance body mist                               1
fragrance mist                                   11
fragrances                                       14
gift sets                                         4
hair perfume                                      1
l'eau de parfum                                   2
lotion                                            4
mist                                              1
oil perfume                                       1
parfum                                            3
parfum, lotion, gloss and blush                   1
perfume                                          55
perfume fragrance mist                            1
perfume gift sets                                 1
perfume oil                                       3
perfume, eau de parfum                            2
pink sugar                                        1
scented oils                                      1
sensuous body moisturizer                         1
shimmer                                           1
shimmering body oil                               1
skin_moisturizer                                  2
solid perfume stick                               1
spray                                             5
toilette spray                                    1
~ body firm advanced body repair treatment ~      1
Name: count, dtype: int64

In [19]:
type_mapping = {
    'eau de parfum': 'Eau de Parfum',
    'eau de perfume': 'Eau de Parfum',
    'eau de parfume': 'Eau de Parfum',
    'edp': 'Eau de Parfum',
    "l'eau de parfum": 'Eau de Parfum',
    'eau de parfum, spray': 'Eau de Parfum',
    'eau de parfum, eau de parfume': 'Eau de Parfum',
    'eau de parfum spray (unisex tester) 3.4 oz': 'Eau de Parfum',
    'eau de parfum supreme': 'Eau de Parfum',
    'eau de parfum 2 pcs set': 'Eau de Parfum',
    'eau de parfum 3 pcs set': 'Eau de Parfum',
    'eau de parfum/perfume': 'Eau de Parfum',
    'perfume, eau de parfum': 'Eau de Parfum',
    'edp and parfum': 'Eau de Parfum',
    '/': 'Eau de Parfum',
    '1': 'Eau de Parfum',
    

    'eau de toilette': 'Eau de Toilette',
    'edt': 'Eau de Toilette',
    'eau de toilette, spray': 'Eau de Toilette',
    'toilette spray': 'Eau de Toilette',
    'eau de toilette spray 3.4 oz': 'Eau de Toilette',

    'eau de cologne': 'Eau de Cologne',
    'cologne': 'Eau de Cologne',
    'cologne spray': 'Eau de Cologne',

    'parfum': 'Parfum',
    'perfume': 'Parfum',
    'extrait de parfum': 'Parfum',
    'extract parfum': 'Parfum',
    'esprit de parfum': 'Parfum',
    'elixir de parfum': 'Parfum',

    'fragrance mist': 'Fragrance Mist',
    'fine fragrance mist': 'Fragrance Mist',
    'fragrance body mist': 'Fragrance Mist',
    'perfume fragrance mist': 'Fragrance Mist',
    'body mist': 'Fragrance Mist',
    'mist': 'Fragrance Mist',

    'perfume oil': 'Perfume Oil',
    'oil perfume': 'Perfume Oil',
    'scented oils': 'Perfume Oil',

    'body spray': 'Body Spray',
    'spray': 'Body Spray',

    'lotion': 'Body Lotion',
    'body lotion': 'Body Lotion',
    'skin_moisturizer': 'Body Lotion',
    'sensuous body moisturizer': 'Body Lotion',

    'deodorant': 'Deodorant',
    'deodorant stick': 'Deodorant',

    'gift sets': 'Gift Set',
    'perfume gift sets': 'Gift Set',
    'discovery set': 'Gift Set'
}

In [20]:
df["type"] = df["type"].replace(type_mapping)
df["type"].value_counts(dropna=False).sort_index(ascending=True)

type
3 pc                                              1
Body Lotion                                       8
Body Spray                                        6
Deodorant                                         2
Eau de Cologne                                   42
Eau de Parfum                                   619
Eau de Toilette                                 201
Fragrance Mist                                   16
Gift Set                                          6
Parfum                                           65
Perfume Oil                                       5
asst                                              1
bath oil                                          1
beauty                                            1
body powder                                       1
cream                                             1
does not apply                                    2
fragrances                                       14
hair perfume                                      1
parfum, lotion, gloss and blush                   1
pink sugar                                        1
shimmer                                           1
shimmering body oil                               1
solid perfume stick                               1
~ body firm advanced body repair treatment ~      1
Name: count, dtype: int64

In [21]:
df[df["type"] == "3 pc"]     #Filter untuk membantu pembuatan mapping

,brand,title,type,price,priceWithCurrency,available,availableText,sold,lastUpdated,itemLocation
74,Elizabeth Arden,Elizabeth Arden White Tea Fragrance Collection...,3 pc,19.45,US $19.45,50.0,50 available / 2 sold,2.0,"May 24, 2024 07:12:19 PDT","Ronkonkoma, New York, United States"

# Cleaning untuk price dan priceWithCure

## Mengambil value angka pada colom "priceWithCurrency"

In [22]:
df["price_c_clean"] = (
    df["priceWithCurrency"]
    .str.extract(r'(\d+(?:\.\d+)?)')[0]
    .astype(float)
)
df[["price","price_c_clean"]]

      price  price_c_clean
0     43.99          43.99
1     79.99          79.99
2     59.99          59.99
3     59.99          59.99
4     29.99          29.99
5     51.99          51.99
6     58.99          58.99
7     52.79          52.79
8     29.99          29.99
9     22.75          22.75
10    39.99          39.99
11    64.99          64.99
12    60.99          60.99
13    43.49          43.49
14    29.20          29.20
15    13.00          13.00
16    39.69          39.69
17    59.99          59.99
18    59.99          59.99
19    11.00          11.00
20    27.00          27.00
21    29.99          29.99
22    16.27          16.27
23    54.95          54.95
24    49.99          49.99
25    84.99          84.99
26    39.99          39.99
27    53.99          53.99
28    99.99          99.99
29    40.92          40.92
30    22.90          22.90
31    42.00          42.00
32    44.88          44.88
33    66.99          66.99
34   129.99         129.99
35    22.99          22.99
36    12.00          12.00
37    32.95          32.95
38    31.05          31.05
39    32.20          32.20
40    17.90          17.90
41    29.75          29.75
42    19.99          19.99
43    43.99          43.99
44    59.99          59.99
45    42.88          42.88
46   100.99         100.99
47    26.05          26.05
48    54.99          54.99
49    49.99          49.99
50    47.49          47.49
51    43.99          43.99
52    32.00          32.00
53    31.50          31.50
54    42.99          42.99
55    98.99          98.99
56    42.00          42.00
57    39.99          39.99
58    27.99          27.99
59    42.99          42.99
60    43.99          43.99
61    15.49          15.49
62    23.25          23.25
63    16.26          16.26
64    49.68          49.68
65    49.99          49.99
66    27.90          27.90
67    49.99          49.99
68    36.79          36.79
69    39.99          39.99
70    48.88          48.88
71    55.99          55.99
72    42.98          42.98
73    15.98          15.98
74    19.45          19.45
75    49.99          49.99
76    20.49          20.49
77    31.00          31.00
78    24.99          24.99
79    19.00          19.00
80    14.00          14.00
81    34.00          34.00
82    49.00          49.00
83    54.99          54.99
84    30.99          30.99
85    16.63          16.63
86    60.00          60.00
87    42.99          42.99
88    19.00          19.00
89    25.27          25.27
90    29.90          29.90
91    20.93          20.93
92    30.98          30.98
93    41.50          41.50
94    64.99          64.99
95    29.99          29.99
96    30.79          30.79
97    39.99          39.99
98    21.27          21.27
99    15.89          15.89
100   10.99          10.99
101   37.88          37.88
102   30.95          30.95
103   25.23          25.23
104   23.88          23.88
105   18.50          18.50
106   20.45          20.45
107   59.99          59.99
108   12.78          12.78
109   64.99          64.99
110   33.99          33.99
111   29.99          29.99
112  100.99         100.99
113   14.75          14.75
114   19.00          19.00
115   33.52          33.52
116  100.99         100.99
117   28.00          28.00
118   49.99          49.99
119    9.70           9.70
120   44.99          44.99
121   33.00          33.00
122   33.80          33.80
123   22.99          22.99
124   49.99          49.99
125   17.89          17.89
126   35.09          35.09
127   25.57          25.57
128   16.44          16.44
129   10.99          10.99
130    7.99           7.99
131   43.99          43.99
132   36.65          36.65
133   29.99          29.99
134   54.99          54.99
135   12.49          12.49
136   49.99          49.99
137    9.25           9.25
138  100.99         100.99
139   50.68          50.68
140   42.00          42.00
141   38.92          38.92
142   49.99          49.99
143   58.99          58.99
144   33.38          33.38
145   29.65          29.65
146   18.63          18.63
147   28.05          28.05
148   55.10          55.10
149   99.99          99.99
150   19.75          19.75
151   34.08          34.08
152   12.95          12.95
153   30.00          30.00
154   12.36          12.36
155   43.99          43.99
156   51.99          51.99
157   79.99          79.99
158   43.69          43.69
159   35.39          35.39
160   34.28          34.28
161   43.32          43.32
162   41.99          41.99
163   29.49          29.49
164   41.99          41.99
165   36.59          36.59
166   33.99          33.99
167   41.99          41.99
168   49.00          49.00
169  119.99         119.99
170   26.99          26.99
171   15.99          15.99
172   19.68          19.68
173   42.28          42.28
174   26.99          26.99
175  109.95         109.95
176   23.75          23.75
177   18.99          18.99
178   33.00          33.00
179   41.49          41.49
180   32.12          32.12
181   55.39          55.39
182   36.99          36.99
183   54.99          54.99
184   28.99          28.99
185   49.99          49.99
186   34.59          34.59
187   39.47          39.47
188   29.90          29.90
189   59.99          59.99
190   20.42          20.42
191   29.99          29.99
192   25.42          25.42
193   59.99          59.99
194   62.99          62.99
195   35.08          35.08
196   95.99          95.99
197   49.99          49.99
198   30.17          30.17
199   37.19          37.19
200   18.79          18.79
201   40.00          40.00
202   79.99          79.99
203   20.44          20.44
204   44.99          44.99
205   14.89          14.89
206   23.95          23.95
207   43.99          43.99
208   59.99          59.99
209   52.78          52.78
210   54.90          54.90
211   43.33          43.33
212   29.45          29.45
213   20.00          20.00
214   29.99          29.99
215   20.48          20.48
216   12.00          12.00
217   22.09          22.09
218   34.38          34.38
219   24.24          24.24
220   21.95          21.95
221   39.89          39.89
222   18.94          18.94
223   24.51          24.51
224   32.99          32.99
225   16.95          16.95
226   33.99          33.99
227   35.73          35.73
228   34.98          34.98
229   59.96          59.96
230   64.88          64.88
231   69.99          69.99
232   25.69          25.69
233   49.68          49.68
234   33.92          33.92
235   24.99          24.99
236   49.99          49.99
237   34.99          34.99
238   30.45          30.45
239   67.50          67.50
240    5.99           5.99
241   15.00          15.00
242   15.99          15.99
243   79.72          79.72
244   33.99          33.99
245   39.98          39.98
246   44.99          44.99
247   44.95          44.95
248   60.37          60.37
249   53.99          53.99
250   30.99          30.99
251   23.90          23.90
252   99.99          99.99
253   26.43          26.43
254   20.00          20.00
255   29.95          29.95
256   15.52          15.52
257   45.99          45.99
258   29.99          29.99
259   27.31          27.31
260   38.99          38.99
261   45.92          45.92
262   12.99          12.99
263   26.99          26.99
264   58.61          58.61
265   86.99          86.99
266   54.00          54.00
267    5.99           5.99
268   24.39          24.39
269   22.99          22.99
270   21.98          21.98
271   76.99          76.99
272   28.99          28.99
273   33.89          33.89
274   59.99          59.99
275    8.99           8.99
276   18.95          18.95
277   20.79          20.79
278   89.99          89.99
279   20.31          20.31
280   34.60          34.60
281   38.14          38.14
282   16.89          16.89
283   12.95          12.95
284   49.81          49.81
285   34.99          34.99
286   29.95          29.95
287   85.56          85.56
288  119.00         119.00
289   27.26          27.26
290   69.99          69.99
291   99.99          99.99
292   48.88          48.88
293   48.99          48.99
294   28.99          28.99
295   37.99          37.99
296   20.99          20.99
297   86.99          86.99
298   29.55          29.55
299    9.99           9.99
300   12.99          12.99
301   26.90          26.90
302   44.78          44.78
303   34.99          34.99
304   14.50          14.50
305   14.95          14.95
306   42.99          42.99
307  100.99         100.99
308   49.99          49.99
309    9.99           9.99
310   28.15          28.15
311   14.74          14.74
312   29.99          29.99
313   35.99          35.99
314   49.99          49.99
315   19.05          19.05
316   29.54          29.54
317   47.80          47.80
318   13.95          13.95
319   59.99          59.99
320   43.00          43.00
321   22.51          22.51
322    9.92           9.92
323   47.65          47.65
324   86.99          86.99
325   41.58          41.58
326   16.87          16.87
327   59.40          59.40
328   43.99          43.99
329   69.99          69.99
330   12.99          12.99
331   11.66          11.66
332   43.15          43.15
333   32.99          32.99
334   15.80          15.80
335   15.00          15.00
336   17.52          17.52
337   38.99          38.99
338   19.83          19.83
339   17.49          17.49
340   19.12          19.12
341   30.90          30.90
342   13.89          13.89
343   12.74          12.74
344   48.00          48.00
345   26.66          26.66
346   33.34          33.34
347   12.00          12.00
348   17.57          17.57
349   20.00          20.00
350   19.99          19.99
351   55.99          55.99
352   38.68          38.68
353   14.45          14.45
354   15.88          15.88
355   32.13          32.13
356   18.99          18.99
357    9.95           9.95
358   20.00          20.00
359   25.25          25.25
360   22.25          22.25
361   21.99          21.99
362   63.99          63.99
363   39.95          39.95
364   49.99          49.99
365   15.77          15.77
366   41.99          41.99
367   17.00          17.00
368   18.99          18.99
369   30.99          30.99
370   49.99          49.99
371   44.99          44.99
372   55.99          55.99
373   41.99          41.99
374   24.50          24.50
375   38.99          38.99
376   12.49          12.49
377   14.40          14.40
378   69.99          69.99
379   44.99          44.99
380   63.00          63.00
381   30.99          30.99
382   12.99          12.99
383   25.99          25.99
384   23.99          23.99
385   25.00          25.00
386   15.42          15.42
387   28.89          28.89
388   33.59          33.59
389   64.99          64.99
390   11.88          11.88
391   43.99          43.99
392   25.66          25.66
393   59.99          59.99
394   52.99          52.99
395   89.99          89.99
396   26.35          26.35
397   79.99          79.99
398  118.99         118.99
399   64.99          64.99
400   41.50          41.50
401    7.95           7.95
402   24.98          24.98
403   64.54          64.54
404   34.77          34.77
405   29.99          29.99
406   29.99          29.99
407   52.99          52.99
408   24.79          24.79
409  269.00         269.00
410    5.50           5.50
411   64.99          64.99
412   29.99          29.99
413   50.73          50.73
414   26.33          26.33
415   46.44          46.44
416   43.98          43.98
417   23.97          23.97
418   44.95          44.95
419   32.49          32.49
420   14.99          14.99
421   29.26          29.26
422   36.99          36.99
423   19.10          19.10
424   19.39          19.39
425   31.00          31.00
426   23.42          23.42
427   15.31          15.31
428   52.99          52.99
429  174.99         174.99
430   69.99          69.99
431   99.99          99.99
432   23.99          23.99
433   50.00          50.00
434   15.25          15.25
435   43.99          43.99
436   34.43          34.43
437   37.88          37.88
438   49.99          49.99
439   42.04          42.04
440   10.00          10.00
441   27.06          27.06
442   55.99          55.99
443   69.98          69.98
444   17.25          17.25
445   29.95          29.95
446   29.99          29.99
447   49.99          49.99
448   43.82          43.82
449   38.00          38.00
450   29.97          29.97
451   52.39          52.39
452   21.95          21.95
453   24.95          24.95
454   18.75          18.75
455   72.00          72.00
456   54.99          54.99
457   18.14          18.14
458   14.70          14.70
459   44.99          44.99
460   34.93          34.93
461   28.90          28.90
462   15.00          15.00
463  128.88         128.88
464    9.94           9.94
465   38.89          38.89
466   74.99          74.99
467   19.41          19.41
468   43.15          43.15
469   27.98          27.98
470   26.15          26.15
471   26.00          26.00
472   40.99          40.99
473   76.50          76.50
474    7.99           7.99
475   78.99          78.99
476   40.00          40.00
477   29.95          29.95
478   21.69          21.69
479   57.63          57.63
480   27.25          27.25
481   23.68          23.68
482   49.99          49.99
483   42.99          42.99
484   99.00          99.00
485    7.99           7.99
486   23.00          23.00
487   99.00          99.00
488   34.36          34.36
489   44.98          44.98
490   42.88          42.88
491   38.99          38.99
492   28.60          28.60
493   45.11          45.11
494   50.07          50.07
495   24.99          24.99
496   59.99          59.99
497   34.95          34.95
498   46.94          46.94
499   17.99          17.99
500   29.00          29.00
501   11.99          11.99
502   86.99          86.99
503   14.45          14.45
504   50.00          50.00
505   50.00          50.00
506   86.99          86.99
507   20.67          20.67
508   21.64          21.64
509   59.99          59.99
510   56.97          56.97
511   29.89          29.89
512   13.76          13.76
513   49.99          49.99
514    9.89           9.89
515   11.99          11.99
516   24.74          24.74
517   71.41          71.41
518   59.99          59.99
519   80.99          80.99
520   24.04          24.04
521   28.68          28.68
522   34.99          34.99
523   15.99          15.99
524   27.99          27.99
525   29.99          29.99
526   20.25          20.25
527   42.00          42.00
528    6.99           6.99
529   79.99          79.99
530   32.88          32.88
531   55.73          55.73
532   16.82          16.82
533   26.99          26.99
534   18.35          18.35
535    4.95           4.95
536   19.90          19.90
537    9.99           9.99
538   19.95          19.95
539   49.99          49.99
540   16.93          16.93
541   19.99          19.99
542   29.95          29.95
543   11.95          11.95
544   15.00          15.00
545   19.54          19.54
546  150.00         150.00
547   44.49          44.49
548   59.99          59.99
549   32.49          32.49
550   14.90          14.90
551   21.95          21.95
552   33.99          33.99
553   29.49          29.49
554   31.23          31.23
555    8.98           8.98
556   37.99          37.99
557   43.99          43.99
558   18.99          18.99
559   14.75          14.75
560   59.32          59.32
561  285.00         285.00
562   13.37          13.37
563   38.49          38.49
564   25.98          25.98
565    9.25           9.25
566   11.95          11.95
567   13.00          13.00
568   42.99          42.99
569   67.99          67.99
570   44.99          44.99
571   16.20          16.20
572   31.41          31.41
573   29.99          29.99
574   20.00          20.00
575   19.95          19.95
576   49.99          49.99
577   79.99          79.99
578   45.99          45.99
579   27.00          27.00
580   22.99          22.99
581   13.99          13.99
582   61.99          61.99
583   99.99          99.99
584   99.99          99.99
585   13.95          13.95
586   31.95          31.95
587   49.51          49.51
588   59.50          59.50
589   99.99          99.99
590   54.99          54.99
591   69.58          69.58
592   59.23          59.23
593   49.99          49.99
594   34.99          34.99
595   35.79          35.79
596   30.89          30.89
597   99.99          99.99
598   99.95          99.95
599   14.94          14.94
600   49.99          49.99
601   29.06          29.06
602  140.00         140.00
603    1.99           1.99
604   54.99          54.99
605   26.14          26.14
606   13.75          13.75
607   17.99          17.99
608   14.99          14.99
609   16.30          16.30
610   18.04          18.04
611   13.88          13.88
612   15.00          15.00
613   32.99          32.99
614   49.99          49.99
615   40.00          40.00
616   29.95          29.95
617   20.00          20.00
618   34.09          34.09
619   55.63          55.63
620   27.25          27.25
621   29.99          29.99
622   25.47          25.47
623    9.99           9.99
624   22.95          22.95
625   18.62          18.62
626   64.94          64.94
627   14.89          14.89
628   79.99          79.99
629   19.24          19.24
630   18.87          18.87
631   19.53          19.53
632   54.42          54.42
633   25.99          25.99
634   32.49          32.49
635   24.77          24.77
636   18.76          18.76
637  100.99         100.99
638   18.90          18.90
639   19.95          19.95
640   14.49          14.49
641    9.99           9.99
642   26.12          26.12
643   15.27          15.27
644   18.00          18.00
645   12.99          12.99
646   13.99          13.99
647   19.88          19.88
648   24.02          24.02
649   32.91          32.91
650   37.99          37.99
651   40.63          40.63
652  128.88         128.88
653   26.40          26.40
654   43.99          43.99
655   43.99          43.99
656   15.49          15.49
657  100.99         100.99
658   27.54          27.54
659   15.99          15.99
660   26.81          26.81
661   38.76          38.76
663   58.50          58.50
664   10.99          10.99
665   42.99          42.99
666   43.99          43.99
667   29.95          29.95
668   34.87          34.87
669   15.99          15.99
670   28.00          28.00
671   16.99          16.99
672   18.00          18.00
673   29.99          29.99
674   17.79          17.79
675   33.00          33.00
676   22.48          22.48
677   49.99          49.99
678   24.99          24.99
679   27.50          27.50
680   45.93          45.93
681    4.95           4.95
682  105.95         105.95
683   26.00          26.00
684   22.53          22.53
685   26.15          26.15
686   39.45          39.45
687   29.99          29.99
688   15.99          15.99
689   14.99          14.99
690   20.71          20.71
691   21.00          21.00
692   53.99          53.99
693   37.00          37.00
694   23.98          23.98
695   11.99          11.99
696   28.99          28.99
697   25.95          25.95
698    6.99           6.99
699   25.56          25.56
700   53.99          53.99
701  103.99         103.99
702   72.72          72.72
703   49.99          49.99
704   59.99          59.99
705   12.99          12.99
706   27.99          27.99
707   15.89          15.89
708   54.90          54.90
709   19.98          19.98
710    7.50           7.50
711   67.49          67.49
712   58.99          58.99
713   30.99          30.99
714   43.30          43.30
715   32.99          32.99
716   20.00          20.00
717   22.97          22.97
718   66.69          66.69
719   44.99          44.99
720   31.14          31.14
721   67.98          67.98
722   29.49          29.49
723   26.95          26.95
724   10.00          10.00
725   37.96          37.96
726   79.99          79.99
727    8.00           8.00
728   42.90          42.90
729  134.50         134.50
730   58.98          58.98
731    9.89           9.89
732   24.00          24.00
733   34.33          34.33
734   54.51          54.51
735   48.99          48.99
736   30.49          30.49
737   38.69          38.69
738   49.99          49.99
739   10.35          10.35

## Membandingkan dengan kolom "price"

In [23]:
df[df["price"] != df["price_c_clean"]]

Empty DataFrame
Columns: [brand, title, type, price, priceWithCurrency, available, availableText, sold, lastUpdated, itemLocation, price_c_clean]
Index: []

kedua kolom memiliki value yang sama sehingga salah satu kolom bisa diabaikan

# Cleanning untuk available, availableText, dan sold

## Memisahkan missing value "availableText" menjadi dataframe baru

In [24]:
df_discontinue = df[df["availableText"].isna()].copy()
df = df[df["availableText"].notna()].copy()
df_discontinue

,brand,title,type,price,priceWithCurrency,available,availableText,sold,lastUpdated,itemLocation,price_c_clean
121,Ellis Brooklyn,NWB Ellis Brooklyn Miami Nectar Eau de Parfum ...,Eau de Parfum,33.00,US $33.00,NaN,NaN,NaN,NaN,"Cranford, New Jersey, United States",33.00
602,Giardini Di Toscana,Bianco Latte EDP by Giardini Di Toscana 100 Ml...,Parfum,140.00,US $140.00,NaN,NaN,NaN,NaN,"Houston, Texas, United States",140.00
732,Chanel,CHANEL Les Eaux De Chanel Paris Eau De Toilett...,Eau de Toilette,24.00,US $24.00,NaN,NaN,NaN,NaN,"Los Angeles, California, United States",24.00
827,Ellis Brooklyn,NWB Ellis Brooklyn Biography Fragrance Discove...,Gift Set,17.00,US $17.00,NaN,NaN,NaN,NaN,"Edison, New Jersey, United States",17.00
839,Lomani,SPICE ADDICT PRIVATE COLLECTION BY LOMANI EDP ...,Eau de Parfum,84.00,US $84.00,NaN,NaN,NaN,NaN,"Hialeah, Florida, United States",84.00
880,Burberry,Burberry Goddess EDP Eau De Parfum Spray 3.3 o...,Eau de Parfum,95.00,US $95.00,NaN,NaN,NaN,NaN,"West Hollywood, California, United States",95.00
927,Snif,"Snif : Sweet Ash .07 FL. OZ. - Juniper, Fir Ba...",Parfum,14.95,US $14.95,NaN,NaN,NaN,NaN,"Philadelphia, Pennsylvania, United States",14.95
983,Burberry,Burberry Her ELIXIR DE PARFUM EDP Intense-Delu...,Eau de Parfum,13.00,US $13.00,NaN,NaN,NaN,NaN,"Chino, California, United States",13.00

## Mengatasi missing value "available"

### Mengisi missing value jika pada "availableText" terdapat text "Last One"

In [25]:
df.loc[
    df["available"].isna() &
    df["availableText"].str.contains("Last One", case=False, na=False),
    'available'
] = 1

### Mengisi missing value jika pada "availableText" terdapat text "Out of Stock"

In [26]:
df.loc[
    df["available"].isna() &
    df["availableText"].str.contains("Out of Stock", case=False, na=False),
    "available"
] = 0

### Mengisi missing value jika pada "availableText" terdapat jumlah available-nya

In [27]:
mask = df["available"].isna()

# untuk "n available"
available_extract = (
    df.loc[mask, "availableText"]
    .str.extract(r'(\d+)\s+available', expand=False)
)

df.loc[mask, "available"] = (
    df.loc[mask, 'available']
    .fillna(pd.to_numeric(available_extract, errors='coerce'))
)

# untuk lot dan jumlah per-lot
lots = df.loc[mask, 'availableText'].str.extract(
    r'(\d+)\s+lots?\s+available',
    expand=False
)

items_per_lot = df.loc[mask, 'availableText'].str.extract(
    r'(\d+)\s+items?\s+per\s+lot',
    expand=False
)

total_items = (
    pd.to_numeric(lots, errors='coerce') *
    pd.to_numeric(items_per_lot, errors='coerce')
)

df.loc[mask, 'available'] = (
    df.loc[mask, 'available']
    .fillna(total_items)
)

# untuk bahasa spanyol
mask_spanish = (
    df['available'].isna() &
    df['availableText'].str.contains(
        r'\d+\s+disponibles?',
        case=False,
        na=False
    )
)

df.loc[mask_spanish, 'available'] = (
    df.loc[mask_spanish, 'availableText']
    .str.extract(r'(\d+)\s+disponibles?', expand=False)
    .astype(int)
)

# input manual
df.loc[990, 'available'] = 32

### Mengisi missing value dengan median untuk Limited quantity

In [28]:
mask_limited = (
    df['available'].isna() &
    df['availableText'].str.contains(
        'Limited quantity available',
        case=False,
        na=False
    )
)

df.loc[mask_limited, 'available'] = df['available'].median()

## Mengatasi missing value untuk kolom "sold"

In [29]:
df[df["sold"].isna()]

,brand,title,type,price,priceWithCurrency,available,availableText,sold,lastUpdated,itemLocation,price_c_clean
4,Khadlaj,Shiyaaka for Men EDP Spray 100ML (3.4 FL.OZ) B...,Eau de Parfum,29.99,US $29.99/ea,10.0,More than 10 available,NaN,NaN,"Little Ferry, New Jersey, United States",29.99
114,Prada,Prada Paradoxe EDP Mini Bottle 7ml/.23oz,Eau de Parfum,19.00,US $19.00,10.0,More than 10 available,NaN,"May 23, 2024 06:27:16 PDT","Bowling Green, Kentucky, United States",19.00
117,Ouai,OUAI Hair & Body Mist In ST. BARTS 3.3oz / 97m...,Fragrance Mist,28.00,US $28.00/ea,2.0,2 available,NaN,NaN,"Beverly Hills, California, United States",28.00
432,Maison Alhambra,DELILAH PERFUME EDP 3.4 OZ BY MAISON ALHAMBRA ...,Eau de Parfum,23.99,US $23.99,10.0,More than 10 available,NaN,NaN,"New York, New York, United States",23.99
496,Victoria'S Secret,Victoria's Secret Bombshell Sundrenched Eau De...,Eau de Parfum,59.99,US $59.99/ea,4.0,4 available,NaN,NaN,"Colorado Springs, Colorado, United States",59.99
551,Jean Couturier,CORIANDRE by JEAN COUTURIER for Women 30ml-1oz...,Eau de Toilette,21.95,US $21.95/ea,5.0,5 available,NaN,NaN,"Los Angeles, California, United States",21.95
617,Dossier,Dossier MUSKY MUSK Eau de Parfum 1.7 Fl oz / 5...,Eau de Parfum,20.00,US $20.00/ea,10.0,More than 10 available,NaN,NaN,"Los Angeles, California, United States",20.00
856,Versace,Bright Crystal de Versace Eau de Toilette 3.0 ...,Eau de Toilette,29.99,US $29.99,2.0,2 disponibles / 3 vendidos,NaN,23 may 2024 02:42:14 EST,"Hamtramck, Michigan, Estados Unidos",29.99

In [30]:
# input manual karna tertera pada "availableText"
df.loc[856, 'sold'] = 3

# mengisi dengan median
df["sold"] = df['sold'].fillna(df['sold'].median())

# Cleaning untuk kolom "lastUpdated"

## Menghapus teks pada kolom

In [31]:
df["lastUpdated"] = df["lastUpdated"].str.strip()
df["lastUpdated"] = (
    df['lastUpdated']
    .str.replace(r'\s+(PDT|PST|EST)$', '', regex=True)
)

## Mengubah tipe data ke datetime

In [32]:
df["lastUpdated"] = pd.to_datetime(
    df["lastUpdated"],
    format = "mixed",
    errors = "coerce"
)

## Memisahkan tanggal dan waktu

In [33]:
df["Date"] = df["lastUpdated"].dt.date
df["Time"] = df["lastUpdated"].dt.time

In [34]:
df.info()

<class 'pandas.DataFrame'>
Index: 991 entries, 0 to 999
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   brand              991 non-null    str
 1   title              991 non-null    str
 2   type               991 non-null    str
 3   price              991 non-null    float64
 4   priceWithCurrency  991 non-null    str
 5   available          991 non-null    float64
 6   availableText      991 non-null    str
 7   sold               991 non-null    float64
 8   lastUpdated        927 non-null    datetime64[us]
 9   itemLocation       991 non-null    str
 10  price_c_clean      991 non-null    float64
 11  Date               927 non-null    object
 12  Time               927 non-null    object
dtypes: datetime64[us](1), float64(4), object(2), str(6)
memory usage: 298.8+ KB

# Memperbaiki tipe data

In [35]:
df[["available","sold"]] = df[["available","sold"]].astype(int)
df["Date"] = pd.to_datetime(df["Date"])
df.info()

<class 'pandas.DataFrame'>
Index: 991 entries, 0 to 999
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   brand              991 non-null    str
 1   title              991 non-null    str
 2   type               991 non-null    str
 3   price              991 non-null    float64
 4   priceWithCurrency  991 non-null    str
 5   available          991 non-null    int64
 6   availableText      991 non-null    str
 7   sold               991 non-null    int64
 8   lastUpdated        927 non-null    datetime64[us]
 9   itemLocation       991 non-null    str
 10  price_c_clean      991 non-null    float64
 11  Date               927 non-null    datetime64[s]
 12  Time               927 non-null    object
dtypes: datetime64[s](1), datetime64[us](1), float64(2), int64(2), object(1), str(6)
memory usage: 298.8+ KB

# Pengecekan nilai tak wajar

In [36]:
df[(df["price"]<0) | (df["available"]<0) | (df["sold"]<0)]

Empty DataFrame
Columns: [brand, title, type, price, priceWithCurrency, available, availableText, sold, lastUpdated, itemLocation, price_c_clean, Date, Time]
Index: []

# Pengecekan outlier

## Outlier kolom type

In [37]:
type_counts = df["type"].value_counts()

Q1 = type_counts.quantile(0.25)
Q3 = type_counts.quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

type_outlier = type_counts[
    (type_counts < lower) |
    (type_counts > upper)
]

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower Bound:", lower)
print("Upper Bound:", upper)
type_outlier

Q1: 1.0
Q3: 8.0
IQR: 7.0
Lower Bound: -9.5
Upper Bound: 18.5

type
Eau de Parfum      615
Eau de Toilette    200
Parfum              63
Eau de Cologne      42
Name: count, dtype: int64

### Mengelompokan outlier ke kategori baru

In [38]:
df["type"].value_counts()

type
Eau de Parfum                                   615
Eau de Toilette                                 200
Parfum                                           63
Eau de Cologne                                   42
Fragrance Mist                                   16
fragrances                                       14
Body Lotion                                       8
Body Spray                                        6
Gift Set                                          5
Perfume Oil                                       5
Deodorant                                         2
does not apply                                    2
~ body firm advanced body repair treatment ~      1
3 pc                                              1
hair perfume                                      1
cream                                             1
shimmer                                           1
parfum, lotion, gloss and blush                   1
bath oil                                          1
asst                                              1
beauty                                            1
shimmering body oil                               1
body powder                                       1
solid perfume stick                               1
pink sugar                                        1
Name: count, dtype: int64

In [39]:
type_counts = df["type"].value_counts()
df["type"] = df["type"].apply(
    lambda x: x if type_counts[x] > 2 else "Others")
        
df["type"].value_counts()

type
Eau de Parfum      615
Eau de Toilette    200
Parfum              63
Eau de Cologne      42
Others              17
Fragrance Mist      16
fragrances          14
Body Lotion          8
Body Spray           6
Gift Set             5
Perfume Oil          5
Name: count, dtype: int64

## Outlier kolom price

In [40]:
Q1 = df["price"].quantile(0.25)
Q3 = df["price"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

price_outlier = df[
    (df["price"] < lower) |
    (df["price"] > upper)
]

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower Bound:", lower)
print("Upper Bound:", upper)
price_outlier["price"].count()

Q1: 20.75
Q3: 49.99
IQR: 29.240000000000002
Lower Bound: -23.11
Upper Bound: 93.85

np.int64(50)

## Outlier kolom available

In [41]:
Q1 = df["available"].quantile(0.25)
Q3 = df["available"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

available_outlier = df[
    (df["available"] < lower) |
    (df["available"] > upper)
]

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower Bound:", lower)
print("Upper Bound:", upper)
available_outlier["available"].count()

Q1: 5.0
Q3: 10.0
IQR: 5.0
Lower Bound: -2.5
Upper Bound: 17.5

np.int64(120)

## Outlier kolom sold

In [42]:
Q1 = df["sold"].quantile(0.25)
Q3 = df["sold"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

sold_outlier = df[
    (df["sold"] < lower) |
    (df["sold"] > upper)
]

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower Bound:", lower)
print("Upper Bound:", upper)
sold_outlier["sold"].count()

Q1: 15.0
Q3: 258.0
IQR: 243.0
Lower Bound: -349.5
Upper Bound: 622.5

np.int64(148)

# Pengecekan setelah cleaning

In [43]:
df.info()

<class 'pandas.DataFrame'>
Index: 991 entries, 0 to 999
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   brand              991 non-null    str
 1   title              991 non-null    str
 2   type               991 non-null    str
 3   price              991 non-null    float64
 4   priceWithCurrency  991 non-null    str
 5   available          991 non-null    int64
 6   availableText      991 non-null    str
 7   sold               991 non-null    int64
 8   lastUpdated        927 non-null    datetime64[us]
 9   itemLocation       991 non-null    str
 10  price_c_clean      991 non-null    float64
 11  Date               927 non-null    datetime64[s]
 12  Time               927 non-null    object
dtypes: datetime64[s](1), datetime64[us](1), float64(2), int64(2), object(1), str(6)
memory usage: 298.5+ KB

In [44]:
df.describe()

,price,available,sold,lastUpdated,price_c_clean,Date
count,991.000000,991.000000,991.000000,927,991.000000,927
mean,39.782069,19.397578,494.177598,2024-05-15 14:00:38.570657,39.782069,2024-05-15 02:46:12
min,1.990000,0.000000,1.000000,2023-07-22 17:43:51,1.990000,2023-07-22 00:00:00
25%,20.750000,5.000000,15.000000,2024-05-16 12:20:20,20.750000,2024-05-16 00:00:00
50%,32.990000,10.000000,52.000000,2024-05-22 07:44:52,32.990000,2024-05-22 00:00:00
75%,49.990000,10.000000,258.000000,2024-05-23 21:05:20,49.990000,2024-05-23 00:00:00
max,299.990000,557.000000,17854.000000,2024-05-24 11:16:44,299.990000,2024-05-24 00:00:00
std,28.904156,48.549104,1368.157831,NaN,28.904156,NaN

In [45]:
df[df.duplicated()]

Empty DataFrame
Columns: [brand, title, type, price, priceWithCurrency, available, availableText, sold, lastUpdated, itemLocation, price_c_clean, Date, Time]
Index: []

# Membuat data frame yang bersih

In [46]:
df_clean = df[["brand","title","type","price","available","sold","itemLocation","Date"]].copy()
df_clean.reset_index(drop=True)
df_clean = df_clean.rename(columns={
    "brand" : "Brand",
    "title" : "Title",
    "type" : "Type",
    "price" : "Price",
    "available" : "Available",
    "sold" : "Sold",
    "itemLocation" : "Item_Location",
    "Date" : "Last_Update(Date)"
})
df_clean

,Brand,Title,Type,Price,Available,Sold,Item_Location,Last_Update(Date)
0,Carolina Herrera,Good Girl by Carolina Herrera 2.7 oz Eau De Pa...,Eau de Parfum,43.99,2,393,"Thomasville, Alabama, United States",2024-05-23
1,As Shown,Parfums de Marly Delina La Rosee Eau de Parfum...,Eau de Parfum,79.99,5,40,"New Jersey, Hong Kong",2024-05-24
2,Prada,PRADA Paradoxe by Prada EDP 3.0oz/90ml Spray P...,Eau de Parfum,59.99,10,35,"Orange, New Jersey, United States",2024-05-14
3,As Show,J'adore Parfum D'eau by Christian 3.4 oz EDP F...,Eau de Parfum,59.99,10,9,"USA, New Jersey, Hong Kong",2024-05-23
4,Khadlaj,Shiyaaka for Men EDP Spray 100ML (3.4 FL.OZ) B...,Eau de Parfum,29.99,10,52,"Little Ferry, New Jersey, United States",NaT
5,Viktor & Rolf,Flowerbomb by Viktor & Rolf 3.4 oz 100ML Eau D...,Eau de Parfum,51.99,8,184,"Warren, Michigan, United States",2024-05-23
6,As Show,PRADA Paradoxe by Prada EDP 3.0oz/90ml Spray P...,Eau de Parfum,58.99,0,18,"Astoria, New York, United States",2024-05-24
7,Versace,Versace Bright Crystal Women EDT 6.7 oz 200 ml...,Eau de Toilette,52.79,6,258,"Dexter, Michigan, United States",2024-05-21
8,Versace,Versace Bright Crystal by Versace for Women ED...,Eau de Toilette,29.99,1,251,"Jamaica, New York, United States",2024-05-23
9,Lattafa,Fakhar by Lattafa Eau de Parfum 3.4 oz / 100 m...,Eau de Parfum,22.75,10,174,"New York, New York, United States",2024-05-24
10,Yves Saint Laurent,Yves Saint Laurent Black Opium 3oz Eau de Parf...,Eau de Parfum,39.99,10,77,"Ecorse, Michigan, United States",2024-05-24
11,Gucci,Gucci Bloom 3.3oz / 3.4oz Eau de Parfum Women'...,Eau de Parfum,64.99,10,35,"Ecorse, Michigan, United States",2024-05-24
12,Carolina Herrera,Very Good Girl GLAM by Carolina Herrera 2.7 oz...,Eau de Parfum,60.99,2,51,"Quinlan, Texas, United States",2024-05-23
13,Carolina Herrera,Good Girl by Carolina Herrera 2.7 fl oz Spray ...,Eau de Parfum,43.49,2,20,"Cincinnati, Ohio, United States",2024-05-22
14,Coach,Coach Floral 3.0 oz EDP eau de parfum spray wo...,Eau de Parfum,29.20,10,505,"Edison, New Jersey, United States",2024-05-08
15,Guerlain,Guerlain NEROLI OUTRENOIR Eau de Parfum 2ml /....,Eau de Parfum,13.00,10,94,"New York, New York, United States",2024-05-24
16,Philosophy,"Amazing Grace by Philosophy, 4 oz EDP Intense ...",Eau de Parfum,39.69,10,234,"Edison, New Jersey, United States",2024-05-24
17,Marc Jacobs,Marc Jacobs Decadence For Women by Marc Jacobs...,Eau de Parfum,59.99,6,34,"New York,USA, Hong Kong",2024-05-22
18,As Shown,PRADA Paradoxe By Prada EDP 3.0oz/90ml Spray P...,Eau de Parfum,59.99,1,43,"New York, New York, United States",2024-05-23
19,Dolce & Gabbana,D&G DOLCE & GABBANA LIGHT BLUE EAU INTENSE WOM...,Eau de Parfum,11.00,10,1613,"Albany, New York, United States",2024-04-05
20,Qrc,Oxytocin-N 15iu Per Spray 1oz (30ml),Body Spray,27.00,10,218,"Oklahoma City, Oklahoma, United States",2024-03-20
21,~ Crepe Erase ~,CREPE ERASE-BODY FIRM ADVANCED BODY REPAIR TRE...,Others,29.99,10,1,"Melrose Park, Illinois, United States",NaT
22,Unbranded,Lattafa YARA by Lattafa 3.4 Oz (100 ml) EDP Ea...,Eau de Parfum,16.27,300,38,"shanghai, China",2024-05-24
23,Yves Saint Laurent,Libre by Yves Saint Laurent YSL 3 oz EDP Perfu...,Eau de Parfum,54.95,1,25,"Stuyvesant Falls, New York, United States",2024-05-24
24,Carolina Herrera,Carolina Herrera Good Girl 2.7 oz EDP Feminine...,Eau de Parfum,49.99,6,183,"Macomb, Michigan, United States",2024-05-23
25,Parfums De Marly,Parfums de Marly Delina 2.5 oz/75 ml EDP Spray...,Eau de Parfum,84.99,4,71,"California or Hong Kong, Hong Kong",2024-05-22
26,Yves Saint Laurent,Mon Paris 3 oz Perfume by Yves Saint Laurent 9...,Eau de Parfum,39.99,8,126,"Farmington, Michigan, United States",2024-05-24
27,Dolce & Gabbana,Dolce & Gabbana Light Blue 6.7 oz Spray Eau De...,Eau de Toilette,53.99,0,54,"Ecorse, Michigan, United States",2024-05-24
28,Ex Nihilo,Blue Taliman by Ex Nihilo Eau De Parfum 3.3oz/...,Eau de Parfum,99.99,4,29,"California or Hong Kong, Hong Kong",2024-05-23
29,Juliette Has A Gun,Not a Perfume by Juliette has a gun 3.3 oz EDP...,Eau de Parfum,40.92,10,1571,"Hackensack, New Jersey, United States",2024-05-24
30,Davidoff,Davidoff Cool Water Sea Rose Eau De Toilette S...,Eau de Toilette,22.90,10,291,"Princeton Junction, New Jersey, United States",2024-05-08
31,Viktor & Rolf,Viktor Rolf Flowerbomb 3.4 oz L'Eau De Parfum ...,Eau de Parfum,42.00,4,406,"Portland, Oregon, United States",2024-05-23
32,Giorgio Armani,Sì Passione by Giorgio Armani For Women 3.4 Oz...,Eau de Parfum,44.88,7,147,"South El Monte, California, United States",2024-05-20
33,Prada,Prada Les infusions De Milano Iris Cedre for W...,Eau de Parfum,66.99,10,3,"Perth Amboy, New Jersey, United States",2024-05-23
34,Roja,Roja Parfums Isola Blu Parfum Unisex 50ml / 1....,Eau de Parfum,129.99,5,37,"United States, Canada",2024-05-24
35,As Shown,Perfume EDP for Women 3.4 oz / 100 ml Brand NEW,Eau de Parfum,22.99,10,11,"CA, China",2024-05-24
36,Parfums De Marly,PDM PARFUMS DE MARLY DELINA EXCLUSIF 1.5ml .05...,Parfum,12.00,10,59,"Albany, New York, United States",NaT
37,Marc Jacobs,Marc Jacobs Daisy Eau So Fresh 4.2 oz / 125 mL...,Eau de Toilette,32.95,10,68,"College Point, New York, United States",2024-05-17
38,Ariana Grande,Cloud by Ariana Grande 3.4 oz / 100 ML EDP Per...,Eau de Parfum,31.05,9,54,"Detroit, Michigan, United States",2024-05-23
39,Versace,Versace Dylan Turquoise by Gianni Versace for ...,Eau de Toilette,32.20,60,157,"Dallas, Texas, United States",2024-05-17
40,Sol De Janeiro,Sol de Janeiro Mini Brazilian Crush Body Fragr...,Fragrance Mist,17.90,10,4,"Round Rock, Texas, United States",2024-05-21
41,Kilian,Love by Kilian Don't Be Shy Eau de Parfum 7.5 ...,Eau de Parfum,29.75,9,80,"Tulsa, Oklahoma, United States",2024-05-24
42,Donna Karan,Donna Karan CASHMERE MIST Deodorant-Anti-Persp...,Others,19.99,10,441,"Elizabeth, New Jersey, United States",2024-05-20
43,Carolina Herrera,Carolina Herrera Good Girl 2.7 oz Eau De Parfu...,Eau de Parfum,43.99,2,16,"San Jose, California, United States",2024-05-24
44,Carolina Herrera,Very Good Girl GLAM by Carolina Herrera 2.7 oz...,Eau de Parfum,59.99,2,21,"Cincinnati, Ohio, United States",2024-05-22
45,Marc Jacobs,Marc Jacobs Daisy Women's Eau De Toilette Spra...,Eau de Toilette,42.88,10,71,"College Point, New York, United States",2024-05-19
46,Parfums De Marly,PARFUMS de MARLY DELINA for WOMEN 2.5 oz (75ml...,Eau de Parfum,100.99,1,49,"Buffalo Mills, Pennsylvania, United States",2024-05-17
47,Juliette Has A Gun,Juliette Has A Gun Discovery Kit includes LUST...,Eau de Parfum,26.05,10,128,"Winter Garden, Florida, United States",2024-05-19
48,As Shown,Flora Gorgeous Jasmine 3.3 oz / 100 ml EDP Per...,Eau de Parfum,54.99,5,60,"USA,California, Hong Kong",2024-05-24
49,Carolina Herrera,Carolina Herrera's Good Girl 2.7 Oz – Women's ...,Eau de Parfum,49.99,6,179,"Dearborn, Michigan, United States",2024-05-21
50,Viktor & Rolf,FLOWERBOMB BY VIKTOR & ROLF 3.4 OZ SPRAY EAU D...,Eau de Parfum,47.49,2,208,"Houston, Texas, United States",2024-05-24
51,Carolina Herrera,Good Girl by Carolina Herrera 2.7 Fl oz Spray ...,Eau de Parfum,43.99,1,166,"Pfafftown, North Carolina, United States",2024-05-23
52,Narciso Rodriguez,Narciso Rodriguez for Her 3.3 / 100ML EDP Perf...,Eau de Parfum,32.00,10,87,"College Point, New York, United States",2024-05-07
53,Coach,Coach Wild Rose 3.0 oz EDP eau de parfum spray...,Eau de Parfum,31.50,10,287,"Edison, New Jersey, United States",2024-05-15
54,Giorgio Armani,My Way by Giorgio Armani 3oz 90ml EDP Perfume ...,Eau de Parfum,42.99,5,243,"College Point, New York, United States",2024-05-23
55,Yves Saint Laurent,"Libre, Eau De Parfum Intense By Yves Saint Lau...",Eau de Parfum,98.99,3,56,"Houston, Texas, United States",2024-04-24
56,Viktor & Rolf,Flowerbomb by Viktor & Rolf 3.4 oz L'Eau de Pa...,Eau de Parfum,42.00,4,404,"Chico, California, United States",2024-05-23
57,Kenzo,Kenzo Amour by Kenzo EDP For Women Spray 3.3 o...,Eau de Parfum,39.99,10,102,"Miami, Florida, United States",2024-05-08
58,Burberry,Burberry Touch by Burberry 3.3 / 3.4 oz EDP Sp...,Eau de Parfum,27.99,10,87,"Warren, Michigan, United States",2024-05-23
59,Carolina Herrera,Good Girl by Carolina Herrera 2.7 Fl oz Eau De...,Eau de Parfum,42.99,2,130,"Santa Cruz, California, United States",2024-05-24
60,Thierry Mugler,Thierry Mugler Angel 1.7oz EDP Women's Perfume...,Eau de Parfum,43.99,6,25,"Detroit, Michigan, United States",2024-05-23
61,Versace,Versace Bright Crystal Eau De Toilette Rollerb...,Eau de Toilette,15.49,10,1089,"Keyport, New Jersey, United States",2024-04-30
62,Lattafa,Lattafa Fakhar EDP Spray 3.4 oz / 100 ml for Men,Eau de Parfum,23.25,10,19,"New York, New York, United States",2024-05-24
63,Donna Karan,"Be Delicious DKNY by Donna Karan, 8 oz Fragran...",Gift Set,16.26,10,110,"Edison, New Jersey, United States",2024-05-24
64,Yves Saint Laurent,Yves Saint Laurent Libre Eau De Parfum 3.0 oz ...,Eau de Parfum,49.68,10,25,"Sacramento, California, United States",2024-05-22
65,Gucci,Gucci Flora Gorgeous Gardenia 3.3oz Women's Ea...,Eau de Toilette,49.99,4,41,"El Monte, California, United States",2024-05-23
66,Dolce & Gabbana,Dolce & Gabbana Light Blue 3.3 /3.4 oz Women’s...,Eau de Toilette,27.90,2,118,"Warren, Michigan, United States",2024-05-22
67,Yves Saint Laurent,New Yves Saint Laurent Libre Eau De Parfum EDP...,Eau de Parfum,49.99,5,15,"Houston, Texas, United States",2024-05-23
68,Juicy Couture,VIVA LA JUICY GOLD COUTURE by Juicy Couture Wo...,Eau de Parfum,36.79,68,1498,"Dallas, Texas, United States",2024-05-24
69,Marc Jacobs,Daisy Eau So Fresh Perfume by Marc Jacobs 4.2 ...,Eau de Toilette,39.99,10,1129,"Lincoln Park, Michigan, United States",2024-05-24
70,Maison Margiela,Maison Margiela Replica Sailing Day Eau de Toi...,Eau de Toilette,48.88,10,14,"College Point, New York, United States",NaT
71,Carolina Herrera,Carolina Herrera Very Good Girl 2.7 oz Daring ...,Eau de Parfum,55.99,6,193,"Macomb, Michigan, United States",2024-05-23
72,Giorgio Armani,My Way by Giorgio Armani 3 oz EDP Perfume for ...,Eau de Parfum,42.98,10,29,"College Point, New York, United States",2024-05-07
73,Jo Malone,Jo Malone London Cologne Spray Travel Size 9ml...,Eau de Cologne,15.98,10,40,"Houston, Texas, United States",2024-05-24
74,Elizabeth Arden,Elizabeth Arden White Tea Fragrance Collection...,Others,19.45,50,2,"Ronkonkoma, New York, United States",2024-05-24
75,Juliette Has A Gun,"Not a Perfume by Juliette Has A Gun, 3.3 oz ED...",Eau de Parfum,49.99,2,288,"Plano, United States",2024-05-23
76,Sol De Janeiro,After Hours by Sol de Janeiro 3OZ/90 ML Fragra...,Body Spray,20.49,8,190,"Dayton,New Jersey, Hong Kong",2024-05-23
77,Narciso Rodriguez,Narciso Rodriguez for Her 3.3 fl oz / 100 ml E...,Eau de Parfum,31.00,4,266,"Bethpage, New York, United States",2024-05-23
78,Urban Outfitters,Urban Outfitters Le Monde Gourmand Eau De Parf...,Eau de Parfum,24.99,9,9,"Kennesaw, Georgia, United States",2024-05-20
79,Dossier,Dossier Ambery Vanilla Eau de Parfum. Size: 50...,Eau de Parfum,19.00,10,10,"Los Angeles, California, United States",NaT
80,Dolce & Gabbana,D&G DOLCE & GABBANA DEVOTION EDP 1.5ml .05fl o...,Eau de Parfum,14.00,10,266,"Albany, New York, United States",NaT
81,Maison Alhambra,Glacier Bold EDP Perfume By Maison Alhambra La...,Eau de Parfum,34.00,10,45,"Astoria, New York, United States",2024-05-18
82,Alt Fragrances,ALT Fragrances - Crystal No. 23 EDP (Inspired ...,Parfum,49.00,10,443,"Van Nuys, California, United States",2024-05-24
83,Estée Lauder,"Estee Lauder Cinnabar Eau De Parfum Spray, 1.7...",Eau de Parfum,54.99,10,17,"Richmond, Texas, United States",2024-03-13
84,Victoria'S Secret,Victoria's Secret Very Sexy Women's Perfume ED...,Eau de Parfum,30.99,10,302,"Flat Lick, Kentucky, United States",2024-05-24
85,Kim Kardashian,KIM KARDASHIAN GOLD Perfume 3.3 / 3.4 oz EDP F...,Eau de Parfum,16.63,37,528,"Dallas, Texas, United States",2024-05-14
86,Thierry Mugler,Angel Standing Star Thierry Mugler 3.3 oz EDP ...,Eau de Parfum,60.00,10,256,"Hamtramck, Michigan, United States",2024-05-22
87,Viktor & Rolf,Flowerbomb by Viktor & Rolf EDP for Women 50 m...,Eau de Parfum,42.99,10,155,"Miami, Florida, United States",2024-03-25
88,Gap,GAP DREAM BODY MIST 8FL OZ/236 mL FREE SHIPPIN...,Fragrance Mist,19.00,10,35,"Hamtramck, Michigan, United States",NaT
89,Cacharel,AMOR AMOR by Cacharel Perfume for women 3.3 oz...,Eau de Toilette,25.27,106,539,"Dallas, Texas, United States",2024-05-21
90,Dolce & Gabbana,Dolce & Gabbana Light Blue 3.3 oz / 3.4 oz EDT...,Eau de Toilette,29.90,10,327,"Walled Lake, Michigan, United States",2024-05-24
91,Jessica Mcclintock,Jessica Mc Clintock by Jessica McClintock 3.4 ...,Eau de Parfum,20.93,10,1484,"Hackensack, New Jersey, United States",2024-05-19
92,As Shown,Women Perfume 3.4 oz / 100 ml Eau De Toilette ...,Eau de Toilette,30.98,10,12,"CA, China",2024-05-24
93,Versace,Versace Bright Crystal Eau De Toilette Spray 6...,Eau de Toilette,41.50,3,255,"San Jose, California, United States",2024-05-24
94,Kilian,Roses on Ice by Kilian 1.7 oz Eau de Parfum Sp...,Eau de Parfum,64.99,5,4,"New Jersey,United States, Hong Kong",2024-05-19
95,Ariana Grande,Ariana Grande Cloud Pink - Charming 3.4oz Eau ...,Eau de Parfum,29.99,9,57,"Dearborn Heights, Michigan, United States",2024-05-22
96,Marc Jacobs,Daisy Eau So Fresh by Marc Jacobs for Women ED...,Eau de Toilette,30.79,3,493,"Jamaica, New York, United States",2024-05-23
97,Yves Saint Laurent,Mon Paris by Yves Saint Laurent 3 fl oz/90 ml ...,Eau de Parfum,39.99,10,66,"Saint Clair Shores, Michigan, United States",2024-05-21
98,Clinique,Clinique Happy by Clinique 3.3 / 3.4 oz Perfum...,Parfum,21.27,2,61,"CA, United States",2024-05-09
99,Unbranded,Yara by Lattafa Perfumes | Eau De Parfum-100ml...,Eau de Parfum,15.89,10,434,"shanghai, China",2024-05-24
100,Valentino,Valentine Milano For Women Perfume 3.4 fl.oz f...,Parfum,10.99,10,94,"Katy, Texas, United States",2024-05-08
101,Giorgio Armani,New Si by Giorgio Armani 3.4 oz / 100 mL EDP P...,Eau de Parfum,37.88,8,108,"College Point, New York, United States",2024-05-24
102,Dolce & Gabbana,Light Blue 3.3 oz by Dolce & Gabbana EDT Perfu...,Eau de Toilette,30.95,8,245,"Sterrett, Alabama, United States",2024-05-24
103,Jimmy Choo,ILLICIT FLOWER by Jimmy Choo for women EDT 3.3...,Eau de Toilette,25.23,8,909,"Dallas, Texas, United States",2024-05-23
104,Calvin Klein,Obsession by Calvin Klein EDP Perfume for Wome...,Eau de Parfum,23.88,10,5587,"Hackensack, New Jersey, United States",2024-05-22
105,Victoria'S Secret,VICTORIA'S SECRET Bombshell Seduction Fine Fra...,Fragrance Mist,18.50,6,23,"Lisle, Illinois, United States",2024-05-21
106,Alfred Sung,SHI by Alfred Sung Perfume for Women EDP 3.3 /...,Eau de Parfum,20.45,110,4308,"Dallas, Texas, United States",2024-05-24
107,As Shown,LIBRE By Yves Saint Laurent YSL Eau de Parfum ...,Eau de Parfum,59.99,10,114,"New Jersey, United States",2024-05-17
108,Gloria Vanderbilt,VANDERBILT by Gloria 3.4 oz 3.3 edt for Women ...,Eau de Toilette,12.78,149,10268,"Dallas, Texas, United States",2024-05-23
109,Prada,PRADA Paradoxe by Prada EDP 3.0oz/90ml Spray P...,Eau de Parfum,64.99,10,123,"New Jersey, United States",2024-05-10
110,Ariana Grande,Ariana Grande Cloud 2.0 Intense Eau De Parfum ...,Eau de Parfum,33.99,9,89,"Las Vegas, Nevada, United States",2024-05-24
111,Dolce & Gabbana,Dolce & Gabbana Light Blue Women 3.4 fl oz 100...,Eau de Toilette,29.99,8,187,"Durham, North Carolina, United States",2024-05-24
112,Valentino,VALENTINO DONNA BORN IN ROMA INTENSE 3.4 oz 10...,Eau de Parfum,100.99,1,47,"Buffalo Mills, Pennsylvania, United States",2024-05-17
113,Parfums,Cabotine De Gres by Parfums 3.3 / 3.4 oz EDT P...,Eau de Toilette,14.75,183,1999,"Dallas, Texas, United States",2024-05-23
114,Prada,Prada Paradoxe EDP Mini Bottle 7ml/.23oz,Eau de Parfum,19.00,10,52,"Bowling Green, Kentucky, United States",2024-05-23
115,Jimmy Choo,JIMMY CHOO by Jimmy Choo 3.3 / 3.4 oz Spray ED...,Eau de Toilette,33.52,131,2846,"Dallas, Texas, United States",2024-05-21
116,Kilian,Good Girl Gone Bad by Kilian 1.7 oz / 50 ml Ea...,Eau de Parfum,100.99,1,48,"Buffalo Mills, Pennsylvania, United States",2024-05-17
117,Ouai,OUAI Hair & Body Mist In ST. BARTS 3.3oz / 97m...,Fragrance Mist,28.00,2,52,"Beverly Hills, California, United States",NaT
118,Lancôme,La Vie Est Belle by Lancome 3.4 Oz – Women's L...,Eau de Parfum,49.99,5,127,"Dearborn, Michigan, United States",2024-05-21
119,Valentino,Valentino Donna Born In Roma Eau De Parfum 2ML...,Eau de Parfum,9.70,10,2,"Miami, Florida, United States",NaT
120,Thierry Mugler,ANGEL Thierry Mugler Eau De parfum Spray Women...,Eau de Parfum,44.99,8,232,"Las Vegas, Nevada, United States",2024-05-24
122,Ariana Grande,Cloud by Ariana Grande 3.4 oz / 100 ML EDP Per...,Eau de Parfum,33.80,8,303,"Sayreville, New Jersey, United States",2024-05-21
123,Lattafa,Fakhar by Lattafa 3.4 oz / 100 ml EDP Spray fo...,Eau de Parfum,22.99,10,8,"New York, New York, United States",2024-05-24
124,As Show,J'adore 3.4 oz/100 ml Eau De Parfum EDP Women ...,Eau de Parfum,49.99,8,22,"USA, New Jersey, Hong Kong",2024-05-23
125,Elizabeth Taylor,Forever Elizabeth by Elizabeth Taylor 3.4 oz S...,Eau de Parfum,17.89,71,5263,"Dallas, Texas, United States",2024-05-20
126,Burberry,Brit Sheer by Burberry 3.3 / 3.4 oz EDT Perfum...,Eau de Toilette,35.09,45,755,"Dallas, Texas, United States",2024-05-23
127,Calvin Klein,OBSESSION NIGHT by Calvin Klein Perfume for Wo...,Eau de Parfum,25.57,194,472,"Dallas, Texas, United States",2024-05-24
128,Elizabeth Taylor,BRILLIANT White Diamonds Elizabeth Taylor wome...,Eau de Toilette,16.44,64,315,"Dallas, Texas, United States",2024-05-24
129,Generic,LA VIDA BELLA POUR FEMME EAU DE PARFUM SPRAY F...,Eau de Parfum,10.99,10,29,"Katy, Texas, United States",2024-05-15
130,Kilian,Kilian Angels' Share Eau De Parfum Sample Spra...,Eau de Parfum,7.99,10,333,"Flushing, New York, United States",2024-04-10
131,Thierry Mugler,Alien by Thierry Mugler EDP for Women REFILLAB...,Eau de Parfum,43.99,10,109,"Miami, Florida, United States",2024-05-08
132,Al Haramain,Al Haramain Amber Oud White Edition EDP 3.4 oz...,fragrances,36.65,3,22,"Brooklyn, New York, United States",2024-05-23
133,Dolce & Gabbana,Dolce & Gabbana Light Blue 3.3 oz / 3.4 oz EDT...,Eau de Toilette,29.99,10,315,"Mogadore, Ohio, United States",2024-05-23
134,As Show,Flora Gorgeous Magnolia By-Gucci Eau De Parfum...,Eau de Parfum,54.99,1,9,"Ithaca, New York, United States",2024-05-23
135,Parfums De Marly,Parfums De Marly Delina EDP Official Carded Sa...,Eau de Parfum,12.49,8,490,"Rocklin, California, United States",2024-05-16
136,Dolce & Gabbana,Dolce & Gabbana The One 2.5 oz / 75 ml Eau De ...,Eau de Parfum,49.99,2,15,"Dunedin, Florida, United States",2024-05-24
137,Al Rehab,Choco Musk Arabian Perfume Spray- 50ml by Al R...,Eau de Parfum,9.25,10,290,"Princeton Junction, New Jersey, United States",2024-04-23
138,Byredo,Byredo Mojave Ghost Eau de Parfum EDP Spray 3....,Eau de Parfum,100.99,1,13,"Oxnard, California, United States",2024-05-21
139,As Shown,New Jo Malone London Wood Sage & Sea Salt Colo...,Eau de Cologne,50.68,3,7,"Austin, Texas, United States",NaT
140,Huda Beauty Kayali,KAYALI EDEN SPARKLING LYCHEE | 39 Eau de Parfu...,Eau de Parfum,42.00,4,11,"Nashville, Tennessee, United States",2024-05-22
141,Coach,COACH Floral Blush by Coach perfume for women ...,Eau de Parfum,38.92,141,2515,"Dallas, Texas, United States",2024-05-23
142,As Show,3.3 oz 100 ml Flora Gorgeous Gardena Eau De Pa...,Eau de Parfum,49.99,4,46,"HongKong, Hong Kong",2024-05-24
143,Unbranded,Versace Dylan 3.4 oz Eau de Parfum Spray Parfu...,Eau de Parfum,58.99,10,12,"College Point, New York, United States",2024-05-22
144,Versace,VERSACE WOMAN by Gianni Versace Perfume for Wo...,Eau de Parfum,33.38,76,2715,"Dallas, Texas, United States",2024-05-23
145,Dolce & Gabbana,Light Blue by Dolce & Gabbana 3.3 / 3.4 oz EDT...,Eau de Toilette,29.65,6,821,"Hamtramck, Michigan, United States",2024-05-23

# Feature engineering

In [47]:
df_clean["Potential_Revenue"] = df_clean["Price"]*df_clean["Available"]
df_clean["Estimated_Total_Sales"] = df_clean["Price"]*df_clean["Sold"]
df_clean

,Brand,Title,Type,Price,Available,Sold,Item_Location,Last_Update(Date),Potential_Revenue,Estimated_Total_Sales
0,Carolina Herrera,Good Girl by Carolina Herrera 2.7 oz Eau De Pa...,Eau de Parfum,43.99,2,393,"Thomasville, Alabama, United States",2024-05-23,87.98,17288.07
1,As Shown,Parfums de Marly Delina La Rosee Eau de Parfum...,Eau de Parfum,79.99,5,40,"New Jersey, Hong Kong",2024-05-24,399.95,3199.60
2,Prada,PRADA Paradoxe by Prada EDP 3.0oz/90ml Spray P...,Eau de Parfum,59.99,10,35,"Orange, New Jersey, United States",2024-05-14,599.90,2099.65
3,As Show,J'adore Parfum D'eau by Christian 3.4 oz EDP F...,Eau de Parfum,59.99,10,9,"USA, New Jersey, Hong Kong",2024-05-23,599.90,539.91
4,Khadlaj,Shiyaaka for Men EDP Spray 100ML (3.4 FL.OZ) B...,Eau de Parfum,29.99,10,52,"Little Ferry, New Jersey, United States",NaT,299.90,1559.48
5,Viktor & Rolf,Flowerbomb by Viktor & Rolf 3.4 oz 100ML Eau D...,Eau de Parfum,51.99,8,184,"Warren, Michigan, United States",2024-05-23,415.92,9566.16
6,As Show,PRADA Paradoxe by Prada EDP 3.0oz/90ml Spray P...,Eau de Parfum,58.99,0,18,"Astoria, New York, United States",2024-05-24,0.00,1061.82
7,Versace,Versace Bright Crystal Women EDT 6.7 oz 200 ml...,Eau de Toilette,52.79,6,258,"Dexter, Michigan, United States",2024-05-21,316.74,13619.82
8,Versace,Versace Bright Crystal by Versace for Women ED...,Eau de Toilette,29.99,1,251,"Jamaica, New York, United States",2024-05-23,29.99,7527.49
9,Lattafa,Fakhar by Lattafa Eau de Parfum 3.4 oz / 100 m...,Eau de Parfum,22.75,10,174,"New York, New York, United States",2024-05-24,227.50,3958.50
10,Yves Saint Laurent,Yves Saint Laurent Black Opium 3oz Eau de Parf...,Eau de Parfum,39.99,10,77,"Ecorse, Michigan, United States",2024-05-24,399.90,3079.23
11,Gucci,Gucci Bloom 3.3oz / 3.4oz Eau de Parfum Women'...,Eau de Parfum,64.99,10,35,"Ecorse, Michigan, United States",2024-05-24,649.90,2274.65
12,Carolina Herrera,Very Good Girl GLAM by Carolina Herrera 2.7 oz...,Eau de Parfum,60.99,2,51,"Quinlan, Texas, United States",2024-05-23,121.98,3110.49
13,Carolina Herrera,Good Girl by Carolina Herrera 2.7 fl oz Spray ...,Eau de Parfum,43.49,2,20,"Cincinnati, Ohio, United States",2024-05-22,86.98,869.80
14,Coach,Coach Floral 3.0 oz EDP eau de parfum spray wo...,Eau de Parfum,29.20,10,505,"Edison, New Jersey, United States",2024-05-08,292.00,14746.00
15,Guerlain,Guerlain NEROLI OUTRENOIR Eau de Parfum 2ml /....,Eau de Parfum,13.00,10,94,"New York, New York, United States",2024-05-24,130.00,1222.00
16,Philosophy,"Amazing Grace by Philosophy, 4 oz EDP Intense ...",Eau de Parfum,39.69,10,234,"Edison, New Jersey, United States",2024-05-24,396.90,9287.46
17,Marc Jacobs,Marc Jacobs Decadence For Women by Marc Jacobs...,Eau de Parfum,59.99,6,34,"New York,USA, Hong Kong",2024-05-22,359.94,2039.66
18,As Shown,PRADA Paradoxe By Prada EDP 3.0oz/90ml Spray P...,Eau de Parfum,59.99,1,43,"New York, New York, United States",2024-05-23,59.99,2579.57
19,Dolce & Gabbana,D&G DOLCE & GABBANA LIGHT BLUE EAU INTENSE WOM...,Eau de Parfum,11.00,10,1613,"Albany, New York, United States",2024-04-05,110.00,17743.00
20,Qrc,Oxytocin-N 15iu Per Spray 1oz (30ml),Body Spray,27.00,10,218,"Oklahoma City, Oklahoma, United States",2024-03-20,270.00,5886.00
21,~ Crepe Erase ~,CREPE ERASE-BODY FIRM ADVANCED BODY REPAIR TRE...,Others,29.99,10,1,"Melrose Park, Illinois, United States",NaT,299.90,29.99
22,Unbranded,Lattafa YARA by Lattafa 3.4 Oz (100 ml) EDP Ea...,Eau de Parfum,16.27,300,38,"shanghai, China",2024-05-24,4881.00,618.26
23,Yves Saint Laurent,Libre by Yves Saint Laurent YSL 3 oz EDP Perfu...,Eau de Parfum,54.95,1,25,"Stuyvesant Falls, New York, United States",2024-05-24,54.95,1373.75
24,Carolina Herrera,Carolina Herrera Good Girl 2.7 oz EDP Feminine...,Eau de Parfum,49.99,6,183,"Macomb, Michigan, United States",2024-05-23,299.94,9148.17
25,Parfums De Marly,Parfums de Marly Delina 2.5 oz/75 ml EDP Spray...,Eau de Parfum,84.99,4,71,"California or Hong Kong, Hong Kong",2024-05-22,339.96,6034.29
26,Yves Saint Laurent,Mon Paris 3 oz Perfume by Yves Saint Laurent 9...,Eau de Parfum,39.99,8,126,"Farmington, Michigan, United States",2024-05-24,319.92,5038.74
27,Dolce & Gabbana,Dolce & Gabbana Light Blue 6.7 oz Spray Eau De...,Eau de Toilette,53.99,0,54,"Ecorse, Michigan, United States",2024-05-24,0.00,2915.46
28,Ex Nihilo,Blue Taliman by Ex Nihilo Eau De Parfum 3.3oz/...,Eau de Parfum,99.99,4,29,"California or Hong Kong, Hong Kong",2024-05-23,399.96,2899.71
29,Juliette Has A Gun,Not a Perfume by Juliette has a gun 3.3 oz EDP...,Eau de Parfum,40.92,10,1571,"Hackensack, New Jersey, United States",2024-05-24,409.20,64285.32
30,Davidoff,Davidoff Cool Water Sea Rose Eau De Toilette S...,Eau de Toilette,22.90,10,291,"Princeton Junction, New Jersey, United States",2024-05-08,229.00,6663.90
31,Viktor & Rolf,Viktor Rolf Flowerbomb 3.4 oz L'Eau De Parfum ...,Eau de Parfum,42.00,4,406,"Portland, Oregon, United States",2024-05-23,168.00,17052.00
32,Giorgio Armani,Sì Passione by Giorgio Armani For Women 3.4 Oz...,Eau de Parfum,44.88,7,147,"South El Monte, California, United States",2024-05-20,314.16,6597.36
33,Prada,Prada Les infusions De Milano Iris Cedre for W...,Eau de Parfum,66.99,10,3,"Perth Amboy, New Jersey, United States",2024-05-23,669.90,200.97
34,Roja,Roja Parfums Isola Blu Parfum Unisex 50ml / 1....,Eau de Parfum,129.99,5,37,"United States, Canada",2024-05-24,649.95,4809.63
35,As Shown,Perfume EDP for Women 3.4 oz / 100 ml Brand NEW,Eau de Parfum,22.99,10,11,"CA, China",2024-05-24,229.90,252.89
36,Parfums De Marly,PDM PARFUMS DE MARLY DELINA EXCLUSIF 1.5ml .05...,Parfum,12.00,10,59,"Albany, New York, United States",NaT,120.00,708.00
37,Marc Jacobs,Marc Jacobs Daisy Eau So Fresh 4.2 oz / 125 mL...,Eau de Toilette,32.95,10,68,"College Point, New York, United States",2024-05-17,329.50,2240.60
38,Ariana Grande,Cloud by Ariana Grande 3.4 oz / 100 ML EDP Per...,Eau de Parfum,31.05,9,54,"Detroit, Michigan, United States",2024-05-23,279.45,1676.70
39,Versace,Versace Dylan Turquoise by Gianni Versace for ...,Eau de Toilette,32.20,60,157,"Dallas, Texas, United States",2024-05-17,1932.00,5055.40
40,Sol De Janeiro,Sol de Janeiro Mini Brazilian Crush Body Fragr...,Fragrance Mist,17.90,10,4,"Round Rock, Texas, United States",2024-05-21,179.00,71.60
41,Kilian,Love by Kilian Don't Be Shy Eau de Parfum 7.5 ...,Eau de Parfum,29.75,9,80,"Tulsa, Oklahoma, United States",2024-05-24,267.75,2380.00
42,Donna Karan,Donna Karan CASHMERE MIST Deodorant-Anti-Persp...,Others,19.99,10,441,"Elizabeth, New Jersey, United States",2024-05-20,199.90,8815.59
43,Carolina Herrera,Carolina Herrera Good Girl 2.7 oz Eau De Parfu...,Eau de Parfum,43.99,2,16,"San Jose, California, United States",2024-05-24,87.98,703.84
44,Carolina Herrera,Very Good Girl GLAM by Carolina Herrera 2.7 oz...,Eau de Parfum,59.99,2,21,"Cincinnati, Ohio, United States",2024-05-22,119.98,1259.79
45,Marc Jacobs,Marc Jacobs Daisy Women's Eau De Toilette Spra...,Eau de Toilette,42.88,10,71,"College Point, New York, United States",2024-05-19,428.80,3044.48
46,Parfums De Marly,PARFUMS de MARLY DELINA for WOMEN 2.5 oz (75ml...,Eau de Parfum,100.99,1,49,"Buffalo Mills, Pennsylvania, United States",2024-05-17,100.99,4948.51
47,Juliette Has A Gun,Juliette Has A Gun Discovery Kit includes LUST...,Eau de Parfum,26.05,10,128,"Winter Garden, Florida, United States",2024-05-19,260.50,3334.40
48,As Shown,Flora Gorgeous Jasmine 3.3 oz / 100 ml EDP Per...,Eau de Parfum,54.99,5,60,"USA,California, Hong Kong",2024-05-24,274.95,3299.40
49,Carolina Herrera,Carolina Herrera's Good Girl 2.7 Oz – Women's ...,Eau de Parfum,49.99,6,179,"Dearborn, Michigan, United States",2024-05-21,299.94,8948.21
50,Viktor & Rolf,FLOWERBOMB BY VIKTOR & ROLF 3.4 OZ SPRAY EAU D...,Eau de Parfum,47.49,2,208,"Houston, Texas, United States",2024-05-24,94.98,9877.92
51,Carolina Herrera,Good Girl by Carolina Herrera 2.7 Fl oz Spray ...,Eau de Parfum,43.99,1,166,"Pfafftown, North Carolina, United States",2024-05-23,43.99,7302.34
52,Narciso Rodriguez,Narciso Rodriguez for Her 3.3 / 100ML EDP Perf...,Eau de Parfum,32.00,10,87,"College Point, New York, United States",2024-05-07,320.00,2784.00
53,Coach,Coach Wild Rose 3.0 oz EDP eau de parfum spray...,Eau de Parfum,31.50,10,287,"Edison, New Jersey, United States",2024-05-15,315.00,9040.50
54,Giorgio Armani,My Way by Giorgio Armani 3oz 90ml EDP Perfume ...,Eau de Parfum,42.99,5,243,"College Point, New York, United States",2024-05-23,214.95,10446.57
55,Yves Saint Laurent,"Libre, Eau De Parfum Intense By Yves Saint Lau...",Eau de Parfum,98.99,3,56,"Houston, Texas, United States",2024-04-24,296.97,5543.44
56,Viktor & Rolf,Flowerbomb by Viktor & Rolf 3.4 oz L'Eau de Pa...,Eau de Parfum,42.00,4,404,"Chico, California, United States",2024-05-23,168.00,16968.00
57,Kenzo,Kenzo Amour by Kenzo EDP For Women Spray 3.3 o...,Eau de Parfum,39.99,10,102,"Miami, Florida, United States",2024-05-08,399.90,4078.98
58,Burberry,Burberry Touch by Burberry 3.3 / 3.4 oz EDP Sp...,Eau de Parfum,27.99,10,87,"Warren, Michigan, United States",2024-05-23,279.90,2435.13
59,Carolina Herrera,Good Girl by Carolina Herrera 2.7 Fl oz Eau De...,Eau de Parfum,42.99,2,130,"Santa Cruz, California, United States",2024-05-24,85.98,5588.70
60,Thierry Mugler,Thierry Mugler Angel 1.7oz EDP Women's Perfume...,Eau de Parfum,43.99,6,25,"Detroit, Michigan, United States",2024-05-23,263.94,1099.75
61,Versace,Versace Bright Crystal Eau De Toilette Rollerb...,Eau de Toilette,15.49,10,1089,"Keyport, New Jersey, United States",2024-04-30,154.90,16868.61
62,Lattafa,Lattafa Fakhar EDP Spray 3.4 oz / 100 ml for Men,Eau de Parfum,23.25,10,19,"New York, New York, United States",2024-05-24,232.50,441.75
63,Donna Karan,"Be Delicious DKNY by Donna Karan, 8 oz Fragran...",Gift Set,16.26,10,110,"Edison, New Jersey, United States",2024-05-24,162.60,1788.60
64,Yves Saint Laurent,Yves Saint Laurent Libre Eau De Parfum 3.0 oz ...,Eau de Parfum,49.68,10,25,"Sacramento, California, United States",2024-05-22,496.80,1242.00
65,Gucci,Gucci Flora Gorgeous Gardenia 3.3oz Women's Ea...,Eau de Toilette,49.99,4,41,"El Monte, California, United States",2024-05-23,199.96,2049.59
66,Dolce & Gabbana,Dolce & Gabbana Light Blue 3.3 /3.4 oz Women’s...,Eau de Toilette,27.90,2,118,"Warren, Michigan, United States",2024-05-22,55.80,3292.20
67,Yves Saint Laurent,New Yves Saint Laurent Libre Eau De Parfum EDP...,Eau de Parfum,49.99,5,15,"Houston, Texas, United States",2024-05-23,249.95,749.85
68,Juicy Couture,VIVA LA JUICY GOLD COUTURE by Juicy Couture Wo...,Eau de Parfum,36.79,68,1498,"Dallas, Texas, United States",2024-05-24,2501.72,55111.42
69,Marc Jacobs,Daisy Eau So Fresh Perfume by Marc Jacobs 4.2 ...,Eau de Toilette,39.99,10,1129,"Lincoln Park, Michigan, United States",2024-05-24,399.90,45148.71
70,Maison Margiela,Maison Margiela Replica Sailing Day Eau de Toi...,Eau de Toilette,48.88,10,14,"College Point, New York, United States",NaT,488.80,684.32
71,Carolina Herrera,Carolina Herrera Very Good Girl 2.7 oz Daring ...,Eau de Parfum,55.99,6,193,"Macomb, Michigan, United States",2024-05-23,335.94,10806.07
72,Giorgio Armani,My Way by Giorgio Armani 3 oz EDP Perfume for ...,Eau de Parfum,42.98,10,29,"College Point, New York, United States",2024-05-07,429.80,1246.42
73,Jo Malone,Jo Malone London Cologne Spray Travel Size 9ml...,Eau de Cologne,15.98,10,40,"Houston, Texas, United States",2024-05-24,159.80,639.20
74,Elizabeth Arden,Elizabeth Arden White Tea Fragrance Collection...,Others,19.45,50,2,"Ronkonkoma, New York, United States",2024-05-24,972.50,38.90
75,Juliette Has A Gun,"Not a Perfume by Juliette Has A Gun, 3.3 oz ED...",Eau de Parfum,49.99,2,288,"Plano, United States",2024-05-23,99.98,14397.12
76,Sol De Janeiro,After Hours by Sol de Janeiro 3OZ/90 ML Fragra...,Body Spray,20.49,8,190,"Dayton,New Jersey, Hong Kong",2024-05-23,163.92,3893.10
77,Narciso Rodriguez,Narciso Rodriguez for Her 3.3 fl oz / 100 ml E...,Eau de Parfum,31.00,4,266,"Bethpage, New York, United States",2024-05-23,124.00,8246.00
78,Urban Outfitters,Urban Outfitters Le Monde Gourmand Eau De Parf...,Eau de Parfum,24.99,9,9,"Kennesaw, Georgia, United States",2024-05-20,224.91,224.91
79,Dossier,Dossier Ambery Vanilla Eau de Parfum. Size: 50...,Eau de Parfum,19.00,10,10,"Los Angeles, California, United States",NaT,190.00,190.00
80,Dolce & Gabbana,D&G DOLCE & GABBANA DEVOTION EDP 1.5ml .05fl o...,Eau de Parfum,14.00,10,266,"Albany, New York, United States",NaT,140.00,3724.00
81,Maison Alhambra,Glacier Bold EDP Perfume By Maison Alhambra La...,Eau de Parfum,34.00,10,45,"Astoria, New York, United States",2024-05-18,340.00,1530.00
82,Alt Fragrances,ALT Fragrances - Crystal No. 23 EDP (Inspired ...,Parfum,49.00,10,443,"Van Nuys, California, United States",2024-05-24,490.00,21707.00
83,Estée Lauder,"Estee Lauder Cinnabar Eau De Parfum Spray, 1.7...",Eau de Parfum,54.99,10,17,"Richmond, Texas, United States",2024-03-13,549.90,934.83
84,Victoria'S Secret,Victoria's Secret Very Sexy Women's Perfume ED...,Eau de Parfum,30.99,10,302,"Flat Lick, Kentucky, United States",2024-05-24,309.90,9358.98
85,Kim Kardashian,KIM KARDASHIAN GOLD Perfume 3.3 / 3.4 oz EDP F...,Eau de Parfum,16.63,37,528,"Dallas, Texas, United States",2024-05-14,615.31,8780.64
86,Thierry Mugler,Angel Standing Star Thierry Mugler 3.3 oz EDP ...,Eau de Parfum,60.00,10,256,"Hamtramck, Michigan, United States",2024-05-22,600.00,15360.00
87,Viktor & Rolf,Flowerbomb by Viktor & Rolf EDP for Women 50 m...,Eau de Parfum,42.99,10,155,"Miami, Florida, United States",2024-03-25,429.90,6663.45
88,Gap,GAP DREAM BODY MIST 8FL OZ/236 mL FREE SHIPPIN...,Fragrance Mist,19.00,10,35,"Hamtramck, Michigan, United States",NaT,190.00,665.00
89,Cacharel,AMOR AMOR by Cacharel Perfume for women 3.3 oz...,Eau de Toilette,25.27,106,539,"Dallas, Texas, United States",2024-05-21,2678.62,13620.53
90,Dolce & Gabbana,Dolce & Gabbana Light Blue 3.3 oz / 3.4 oz EDT...,Eau de Toilette,29.90,10,327,"Walled Lake, Michigan, United States",2024-05-24,299.00,9777.30
91,Jessica Mcclintock,Jessica Mc Clintock by Jessica McClintock 3.4 ...,Eau de Parfum,20.93,10,1484,"Hackensack, New Jersey, United States",2024-05-19,209.30,31060.12
92,As Shown,Women Perfume 3.4 oz / 100 ml Eau De Toilette ...,Eau de Toilette,30.98,10,12,"CA, China",2024-05-24,309.80,371.76
93,Versace,Versace Bright Crystal Eau De Toilette Spray 6...,Eau de Toilette,41.50,3,255,"San Jose, California, United States",2024-05-24,124.50,10582.50
94,Kilian,Roses on Ice by Kilian 1.7 oz Eau de Parfum Sp...,Eau de Parfum,64.99,5,4,"New Jersey,United States, Hong Kong",2024-05-19,324.95,259.96
95,Ariana Grande,Ariana Grande Cloud Pink - Charming 3.4oz Eau ...,Eau de Parfum,29.99,9,57,"Dearborn Heights, Michigan, United States",2024-05-22,269.91,1709.43
96,Marc Jacobs,Daisy Eau So Fresh by Marc Jacobs for Women ED...,Eau de Toilette,30.79,3,493,"Jamaica, New York, United States",2024-05-23,92.37,15179.47
97,Yves Saint Laurent,Mon Paris by Yves Saint Laurent 3 fl oz/90 ml ...,Eau de Parfum,39.99,10,66,"Saint Clair Shores, Michigan, United States",2024-05-21,399.90,2639.34
98,Clinique,Clinique Happy by Clinique 3.3 / 3.4 oz Perfum...,Parfum,21.27,2,61,"CA, United States",2024-05-09,42.54,1297.47
99,Unbranded,Yara by Lattafa Perfumes | Eau De Parfum-100ml...,Eau de Parfum,15.89,10,434,"shanghai, China",2024-05-24,158.90,6896.26
100,Valentino,Valentine Milano For Women Perfume 3.4 fl.oz f...,Parfum,10.99,10,94,"Katy, Texas, United States",2024-05-08,109.90,1033.06
101,Giorgio Armani,New Si by Giorgio Armani 3.4 oz / 100 mL EDP P...,Eau de Parfum,37.88,8,108,"College Point, New York, United States",2024-05-24,303.04,4091.04
102,Dolce & Gabbana,Light Blue 3.3 oz by Dolce & Gabbana EDT Perfu...,Eau de Toilette,30.95,8,245,"Sterrett, Alabama, United States",2024-05-24,247.60,7582.75
103,Jimmy Choo,ILLICIT FLOWER by Jimmy Choo for women EDT 3.3...,Eau de Toilette,25.23,8,909,"Dallas, Texas, United States",2024-05-23,201.84,22934.07
104,Calvin Klein,Obsession by Calvin Klein EDP Perfume for Wome...,Eau de Parfum,23.88,10,5587,"Hackensack, New Jersey, United States",2024-05-22,238.80,133417.56
105,Victoria'S Secret,VICTORIA'S SECRET Bombshell Seduction Fine Fra...,Fragrance Mist,18.50,6,23,"Lisle, Illinois, United States",2024-05-21,111.00,425.50
106,Alfred Sung,SHI by Alfred Sung Perfume for Women EDP 3.3 /...,Eau de Parfum,20.45,110,4308,"Dallas, Texas, United States",2024-05-24,2249.50,88098.60
107,As Shown,LIBRE By Yves Saint Laurent YSL Eau de Parfum ...,Eau de Parfum,59.99,10,114,"New Jersey, United States",2024-05-17,599.90,6838.86
108,Gloria Vanderbilt,VANDERBILT by Gloria 3.4 oz 3.3 edt for Women ...,Eau de Toilette,12.78,149,10268,"Dallas, Texas, United States",2024-05-23,1904.22,131225.04
109,Prada,PRADA Paradoxe by Prada EDP 3.0oz/90ml Spray P...,Eau de Parfum,64.99,10,123,"New Jersey, United States",2024-05-10,649.90,7993.77
110,Ariana Grande,Ariana Grande Cloud 2.0 Intense Eau De Parfum ...,Eau de Parfum,33.99,9,89,"Las Vegas, Nevada, United States",2024-05-24,305.91,3025.11
111,Dolce & Gabbana,Dolce & Gabbana Light Blue Women 3.4 fl oz 100...,Eau de Toilette,29.99,8,187,"Durham, North Carolina, United States",2024-05-24,239.92,5608.13
112,Valentino,VALENTINO DONNA BORN IN ROMA INTENSE 3.4 oz 10...,Eau de Parfum,100.99,1,47,"Buffalo Mills, Pennsylvania, United States",2024-05-17,100.99,4746.53
113,Parfums,Cabotine De Gres by Parfums 3.3 / 3.4 oz EDT P...,Eau de Toilette,14.75,183,1999,"Dallas, Texas, United States",2024-05-23,2699.25,29485.25
114,Prada,Prada Paradoxe EDP Mini Bottle 7ml/.23oz,Eau de Parfum,19.00,10,52,"Bowling Green, Kentucky, United States",2024-05-23,190.00,988.00
115,Jimmy Choo,JIMMY CHOO by Jimmy Choo 3.3 / 3.4 oz Spray ED...,Eau de Toilette,33.52,131,2846,"Dallas, Texas, United States",2024-05-21,4391.12,95397.92
116,Kilian,Good Girl Gone Bad by Kilian 1.7 oz / 50 ml Ea...,Eau de Parfum,100.99,1,48,"Buffalo Mills, Pennsylvania, United States",2024-05-17,100.99,4847.52
117,Ouai,OUAI Hair & Body Mist In ST. BARTS 3.3oz / 97m...,Fragrance Mist,28.00,2,52,"Beverly Hills, California, United States",NaT,56.00,1456.00
118,Lancôme,La Vie Est Belle by Lancome 3.4 Oz – Women's L...,Eau de Parfum,49.99,5,127,"Dearborn, Michigan, United States",2024-05-21,249.95,6348.73
119,Valentino,Valentino Donna Born In Roma Eau De Parfum 2ML...,Eau de Parfum,9.70,10,2,"Miami, Florida, United States",NaT,97.00,19.40
120,Thierry Mugler,ANGEL Thierry Mugler Eau De parfum Spray Women...,Eau de Parfum,44.99,8,232,"Las Vegas, Nevada, United States",2024-05-24,359.92,10437.68
122,Ariana Grande,Cloud by Ariana Grande 3.4 oz / 100 ML EDP Per...,Eau de Parfum,33.80,8,303,"Sayreville, New Jersey, United States",2024-05-21,270.40,10241.40
123,Lattafa,Fakhar by Lattafa 3.4 oz / 100 ml EDP Spray fo...,Eau de Parfum,22.99,10,8,"New York, New York, United States",2024-05-24,229.90,183.92
124,As Show,J'adore 3.4 oz/100 ml Eau De Parfum EDP Women ...,Eau de Parfum,49.99,8,22,"USA, New Jersey, Hong Kong",2024-05-23,399.92,1099.78
125,Elizabeth Taylor,Forever Elizabeth by Elizabeth Taylor 3.4 oz S...,Eau de Parfum,17.89,71,5263,"Dallas, Texas, United States",2024-05-20,1270.19,94155.07
126,Burberry,Brit Sheer by Burberry 3.3 / 3.4 oz EDT Perfum...,Eau de Toilette,35.09,45,755,"Dallas, Texas, United States",2024-05-23,1579.05,26492.95
127,Calvin Klein,OBSESSION NIGHT by Calvin Klein Perfume for Wo...,Eau de Parfum,25.57,194,472,"Dallas, Texas, United States",2024-05-24,4960.58,12069.04
128,Elizabeth Taylor,BRILLIANT White Diamonds Elizabeth Taylor wome...,Eau de Toilette,16.44,64,315,"Dallas, Texas, United States",2024-05-24,1052.16,5178.60
129,Generic,LA VIDA BELLA POUR FEMME EAU DE PARFUM SPRAY F...,Eau de Parfum,10.99,10,29,"Katy, Texas, United States",2024-05-15,109.90,318.71
130,Kilian,Kilian Angels' Share Eau De Parfum Sample Spra...,Eau de Parfum,7.99,10,333,"Flushing, New York, United States",2024-04-10,79.90,2660.67

In [48]:
print("Potential Revenue:",df_clean["Potential_Revenue"].sum())
print("Estimated Total Sales:",df_clean["Estimated_Total_Sales"].sum().round(2))

Potential Revenue: 571049.99
Estimated Total Sales: 13898684.79